@extends('admin.layout')

@section('title', 'Ads & attribution | Trans Globe Indore LMS')
@section('crumb', 'Ads & attribution')

@section('content')
<style>
    .ads-page{display:grid;gap:20px}.ads-page>.grid{display:grid!important;gap:20px!important}.ads-page .dash-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.ads-page .dash-metric{position:relative;isolation:isolate;display:flex;min-height:148px;flex-direction:column;align-items:flex-start;overflow:hidden;padding:22px 24px;border:1px solid var(--admin-line);background:linear-gradient(145deg,#fff 0%,#fff 68%,#fff8f8 100%)}.ads-page .dash-metric::after{position:absolute;z-index:-1;right:-42px;bottom:-62px;width:150px;height:150px;border:22px solid rgba(227,30,36,.06);border-radius:50%;content:''}.ads-page .dash-metric__icon{display:grid;width:52px;height:52px;place-items:center;flex:0 0 52px;margin-bottom:16px;border-radius:15px;background:var(--admin-primary-soft);color:var(--admin-primary)}.ads-page .dash-metric__icon--success{background:#e9fbf7;color:#13a98e}.ads-page .dash-metric__icon--warning{background:#fff8e9;color:#e99500}.ads-page .dash-metric__icon svg{width:24px;height:24px;fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.8}.ads-page .dash-metric>div{width:100%;min-width:0}.ads-page .dash-metric>div>span,.ads-page .dash-metric>div>small{display:block}.ads-page .dash-metric>div>span{color:var(--admin-muted);font-size:12px;font-weight:500}.ads-page .dash-metric strong{display:block;margin-top:5px;color:var(--admin-ink);font-size:30px;letter-spacing:-.06em;line-height:1}.ads-page .dash-metric small{margin-top:7px;color:#91a0b7;font-size:11px;line-height:1.35}.ads-page .campaign-panel{overflow:hidden}.ads-page .ads-forms{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.ads-page .ads-forms .editor{display:block!important}.ads-page .ads-forms .panel{height:100%}.ads-page .metrics-filter{display:grid;grid-template-columns:minmax(180px,1fr) minmax(180px,1fr) 170px auto;gap:10px;padding:16px 20px;border:1px solid var(--admin-line);border-radius:16px;background:#fff}.ads-page .daily-form{grid-column:1/-1}@media(max-width:760px){.ads-page .dash-summary,.ads-page .ads-forms{grid-template-columns:1fr}.ads-page .dash-metric{min-height:136px}.ads-page .metrics-filter{grid-template-columns:1fr}.ads-page .daily-form{grid-column:auto}}
</style>
<div class="ads-page">
<div class="page-head"><div><span class="eyebrow">Performance centre</span><h1>Ads &amp; attribution</h1></div><p>See spend, visibility, campaign progress and lead quality in one place.</p></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<section class="grid" style="gap:18px">
    <form class="metrics-filter" method="get" action="{{ route('admin.ads.index') }}"><input class="input" type="date" name="from" value="{{ $from }}" aria-label="From date"><input class="input" type="date" name="to" value="{{ $to }}" aria-label="To date"><select class="select" name="destination"><option value="">All destinations</option>@foreach($destinations as $destination)<option value="{{ $destination }}" @selected(request('destination') === $destination)>{{ $destination }}</option>@endforeach</select><button class="button" type="submit">Apply range</button></form>
    <div class="dash-summary"><article class="dash-metric"><span class="dash-metric__icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3v18M16 7.5c0-1.4-1.6-2.5-4-2.5s-4 1.1-4 2.5 1.6 2.5 4 2.5 4 1.1 4 2.5-1.6 2.5-4 2.5-4 1.1-4 2.5 1.6 2.5 4 2.5 4-1.1 4-2.5"/></svg></span><div><span>Total spend</span><strong>{{ number_format($totals['spend'], 2) }}</strong><small>Selected period</small></div></article><article class="dash-metric"><span class="dash-metric__icon dash-metric__icon--success" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><path d="M3.5 20a5.5 5.5 0 0 1 11 0M16 11a3 3 0 1 0 0-6M16 14a5 5 0 0 1 4.5 6"/></svg></span><div><span>Ad leads</span><strong>{{ number_format($totals['leads']) }}</strong><small>{{ number_format($totals['qualified_leads']) }} qualified</small></div></article><article class="dash-metric"><span class="dash-metric__icon dash-metric__icon--warning" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 19V5M4 19h16M7 15l3-4 3 2 4-6"/></svg></span><div><span>Click-through rate</span><strong>{{ $totals['impressions'] ? number_format(($totals['clicks'] / $totals['impressions']) * 100, 2) : '0.00' }}%</strong><small>{{ number_format($totals['clicks']) }} clicks · {{ number_format($totals['impressions']) }} impressions</small></div></article></div>
    <section class="panel campaign-panel"><div class="panel__head"><div><h2>Campaign performance</h2><span>Filter by provider, destination or status; connect external IDs for future sync.</span></div></div><div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Account</th><th>Landing page</th><th>Spend</th><th>Leads</th><th>Quality</th><th>Status</th></tr></thead><tbody>@forelse($campaigns as $campaign)<tr><td><span class="student">{{ $campaign->name }}</span><span class="sub">{{ $campaign->objective ?: 'Objective not set' }}</span></td><td><span class="pill">{{ strtoupper($campaign->provider) }}</span><span class="sub">{{ $campaign->account_name }}</span></td><td><span class="sub">{{ $campaign->landing_page ?: 'Not mapped' }}</span><span class="sub">{{ $campaign->destination ?: 'All destinations' }}</span></td><td><span class="student">{{ number_format($campaign->spend, 2) }}</span><span class="sub">{{ number_format($campaign->clicks) }} clicks</span></td><td><span class="student">{{ number_format($campaign->leads) }}</span><span class="sub">{{ number_format($campaign->conversions) }} conversions</span></td><td><span class="student">{{ $campaign->leads ? number_format(($campaign->qualified_leads / $campaign->leads) * 100, 1) : '0.0' }}%</span><span class="sub">qualified</span></td><td><span class="pill">{{ ucfirst($campaign->status) }}</span></td></tr>@empty<tr><td colspan="7"><div class="empty"><h3>No campaigns yet</h3><p>Add an account and campaign below, then import daily metrics from your ad provider.</p></div></td></tr>@endforelse</tbody></table></div></section>
    @can('ads.manage')<section class="ads-forms"><form class="panel editor__fields" method="post" action="{{ route('admin.ads.accounts.store') }}">@csrf<h2>Add ad account</h2><div class="field"><label>Provider</label><select class="select" name="provider"><option value="google">Google Ads</option><option value="meta">Meta Ads</option><option value="linkedin">LinkedIn Ads</option><option value="tiktok">TikTok Ads</option><option value="other">Other</option></select></div><div class="field"><label>Account name</label><input class="input" name="name" required placeholder="Google Ads · Trans Globe"></div><div class="field"><label>External account ID</label><input class="input" name="external_account_id" placeholder="Customer or ad account ID"></div><button class="button" type="submit">Add account</button></form><form class="panel editor__fields" method="post" action="{{ route('admin.ads.campaigns.store') }}">@csrf<h2>Add campaign</h2><div class="field"><label>Account</label><select class="select" name="ad_account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ strtoupper($account->provider) }}</option>@endforeach</select></div><div class="field"><label>Campaign name</label><input class="input" name="name" required></div><div class="field"><label>Landing page / destination</label><input class="input" name="landing_page" placeholder="/promotions/…"><input class="input" name="destination" placeholder="Australia"></div><button class="button" type="submit">Add campaign</button></form><form class="panel editor__fields daily-form" method="post" action="{{ route('admin.ads.performance.store') }}">@csrf<h2>Import daily performance</h2><div class="field"><label>Campaign</label><select class="select" name="ad_campaign_id" required>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}">{{ $campaign->name }}</option>@endforeach</select></div><div class="field"><label>Date</label><input class="input" type="date" name="metric_date" value="{{ now()->toDateString() }}" required></div><div class="field"><label>Spend · impressions · clicks · leads · qualified leads · conversions</label><input class="input" name="spend" placeholder="0.00"><input class="input" name="impressions" placeholder="0"><input class="input" name="clicks" placeholder="0"><input class="input" name="leads" placeholder="0"><input class="input" name="qualified_leads" placeholder="0"><input class="input" name="conversions" placeholder="0"></div><button class="button" type="submit">Save daily metrics</button></form></section>@endcan
</section>
</div>
@endsection
