@extends('admin.layout')

@section('title', 'Ads & attribution | Trans Globe Indore LMS')
@section('crumb', 'Ads & attribution')

@section('content')
<div class="page-head"><div><span class="eyebrow">Performance centre</span><h1>Ads &amp; attribution</h1></div><p>See spend, visibility, campaign progress and lead quality in one place.</p></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<section class="grid" style="gap:18px">
    <form class="filters" method="get" action="{{ route('admin.ads.index') }}"><input class="input" type="date" name="from" value="{{ $from }}" aria-label="From date"><input class="input" type="date" name="to" value="{{ $to }}" aria-label="To date"><select class="select" name="destination"><option value="">All destinations</option>@foreach($destinations as $destination)<option value="{{ $destination }}" @selected(request('destination') === $destination)>{{ $destination }}</option>@endforeach</select><button class="button" type="submit">Apply range</button></form>
    <div class="dash-summary"><article class="dash-metric"><span class="dash-metric__icon">Spend</span><div><span>Total spend</span><strong>{{ number_format($totals['spend'], 2) }}</strong><small>Selected period</small></div></article><article class="dash-metric"><span class="dash-metric__icon dash-metric__icon--success">Leads</span><div><span>Ad leads</span><strong>{{ number_format($totals['leads']) }}</strong><small>{{ number_format($totals['qualified_leads']) }} qualified</small></div></article><article class="dash-metric"><span class="dash-metric__icon dash-metric__icon--warning">CTR</span><div><span>Click-through rate</span><strong>{{ $totals['impressions'] ? number_format(($totals['clicks'] / $totals['impressions']) * 100, 2) : '0.00' }}%</strong><small>{{ number_format($totals['clicks']) }} clicks · {{ number_format($totals['impressions']) }} impressions</small></div></article></div>
    <section class="panel"><div class="panel__head"><div><h2>Campaign performance</h2><span>Filter by provider, destination or status; connect external IDs for future sync.</span></div></div><div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Account</th><th>Landing page</th><th>Spend</th><th>Leads</th><th>Quality</th><th>Status</th></tr></thead><tbody>@forelse($campaigns as $campaign)<tr><td><span class="student">{{ $campaign->name }}</span><span class="sub">{{ $campaign->objective ?: 'Objective not set' }}</span></td><td><span class="pill">{{ strtoupper($campaign->provider) }}</span><span class="sub">{{ $campaign->account_name }}</span></td><td><span class="sub">{{ $campaign->landing_page ?: 'Not mapped' }}</span><span class="sub">{{ $campaign->destination ?: 'All destinations' }}</span></td><td><span class="student">{{ number_format($campaign->spend, 2) }}</span><span class="sub">{{ number_format($campaign->clicks) }} clicks</span></td><td><span class="student">{{ number_format($campaign->leads) }}</span><span class="sub">{{ number_format($campaign->conversions) }} conversions</span></td><td><span class="student">{{ $campaign->leads ? number_format(($campaign->qualified_leads / $campaign->leads) * 100, 1) : '0.0' }}%</span><span class="sub">qualified</span></td><td><span class="pill">{{ ucfirst($campaign->status) }}</span></td></tr>@empty<tr><td colspan="7"><div class="empty"><h3>No campaigns yet</h3><p>Add an account and campaign below, then import daily metrics from your ad provider.</p></div></td></tr>@endforelse</tbody></table></div></section>
    @can('ads.manage')<section class="editor" style="grid-template-columns:1fr 1fr"><form class="panel editor__fields" method="post" action="{{ route('admin.ads.accounts.store') }}">@csrf<h2>Add ad account</h2><div class="field"><label>Provider</label><select class="select" name="provider"><option value="google">Google Ads</option><option value="meta">Meta Ads</option><option value="linkedin">LinkedIn Ads</option><option value="tiktok">TikTok Ads</option><option value="other">Other</option></select></div><div class="field"><label>Account name</label><input class="input" name="name" required placeholder="Google Ads · Trans Globe"></div><div class="field"><label>External account ID</label><input class="input" name="external_account_id" placeholder="Customer or ad account ID"></div><button class="button" type="submit">Add account</button></form><form class="panel editor__fields" method="post" action="{{ route('admin.ads.campaigns.store') }}">@csrf<h2>Add campaign</h2><div class="field"><label>Account</label><select class="select" name="ad_account_id" required>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ strtoupper($account->provider) }}</option>@endforeach</select></div><div class="field"><label>Campaign name</label><input class="input" name="name" required></div><div class="field"><label>Landing page / destination</label><input class="input" name="landing_page" placeholder="/promotions/…"><input class="input" name="destination" placeholder="Australia"></div><button class="button" type="submit">Add campaign</button></form></section><form class="panel editor__fields" method="post" action="{{ route('admin.ads.performance.store') }}">@csrf<h2>Import daily performance</h2><div class="field"><label>Campaign</label><select class="select" name="ad_campaign_id" required>@foreach($campaigns as $campaign)<option value="{{ $campaign->id }}">{{ $campaign->name }}</option>@endforeach</select></div><div class="field"><label>Date</label><input class="input" type="date" name="metric_date" value="{{ now()->toDateString() }}" required></div><div class="field"><label>Spend · impressions · clicks · leads · qualified leads · conversions</label><input class="input" name="spend" placeholder="0.00"><input class="input" name="impressions" placeholder="0"><input class="input" name="clicks" placeholder="0"><input class="input" name="leads" placeholder="0"><input class="input" name="qualified_leads" placeholder="0"><input class="input" name="conversions" placeholder="0"></div><button class="button" type="submit">Save daily metrics</button></form>@endcan
</section>
@endsection
