@include('mirror.partials.header')
@include('mirror.partials.mobile-destination-nav', ['mobileBackHref' => url('/scholarships'), 'mobileBackLabel' => 'Back to scholarships'])
@php($detailUrl = url()->current())
@php($scholarshipDestination = \App\Support\DestinationCatalog::find($scholarship['slug']))
@php($scholarshipMedia = $scholarshipDestination['gallery'] ?? [['src' => $scholarship['image'], 'alt' => $scholarship['image_alt'], 'label' => 'Scholarship planning'], ['src' => 'assets/transglobe/services/services-team.avif', 'alt' => 'Counsellors planning a study-abroad route', 'label' => 'Expert guidance'], ['src' => 'assets/transglobe/services/services-campus.avif', 'alt' => 'International university campus', 'label' => 'Your future campus']])
@php($scholarshipUniversities = $scholarshipDestination['universities'] ?? \App\Support\DetailPageAssets::universityNetwork())

<style>
    :root { --sdn-navy:#0e2145; --sdn-red:#e31e24; --sdn-soft:#f4f7fb; --sdn-ink:#15294d; --sdn-muted:#64748b; --sdn-line:#dfe7f0; }
    .sdn-page { overflow: clip; background:#fff; color:var(--sdn-ink); } .sdn-wrap { width:min(1260px,calc(100% - 48px)); margin-inline:auto; } .sdn-section { padding:90px 0; scroll-margin-top:96px; } .sdn-section--soft { background:var(--sdn-soft); }
    .sdn-kicker { display:inline-flex; align-items:center; gap:10px; color:var(--sdn-red); font-size:12px; font-weight:800; letter-spacing:.13em; text-transform:uppercase; } .sdn-kicker::before { width:28px; height:2px; background:currentColor; content:''; }
    .sdn-title { max-width:750px; margin:14px 0 0; color:var(--sdn-navy); font-size:clamp(34px,4vw,50px); line-height:1.1; font-weight:800; letter-spacing:-.045em; text-wrap:balance; } .sdn-lead { max-width:700px; margin:16px 0 0; color:var(--sdn-muted); font-size:17px; line-height:1.75; } .sdn-center { text-align:center; } .sdn-center .sdn-title,.sdn-center .sdn-lead { margin-inline:auto; }
    .sdn-button { display:inline-flex; min-height:52px; align-items:center; justify-content:center; gap:9px; padding:0 23px; border:1px solid transparent; border-radius:14px; background:var(--sdn-red); color:#fff!important; font-size:14px; font-weight:800; transition:transform .2s ease,background .2s ease; } .sdn-button:hover { color:#fff; background:#c81920; transform:translateY(-2px); } .sdn-button--ghost { border-color:rgba(255,255,255,.34); background:rgba(255,255,255,.08); } .sdn-button--ghost:hover { color:var(--sdn-navy)!important; border-color:#fff; background:#fff; } .sdn-page :is(a,summary):focus-visible { outline:3px solid rgba(227,30,36,.35); outline-offset:3px; }
    .sdn-hero { padding:128px 0 0; background:var(--sdn-soft); } .sdn-hero__shell { position:relative; min-height:560px; overflow:hidden; display:flex; align-items:flex-end; border-radius:35px; background:var(--sdn-navy); box-shadow:0 26px 65px rgba(14,33,69,.2); } .sdn-hero__image,.sdn-hero__overlay { position:absolute; inset:0; width:100%; height:100%; } .sdn-hero__image { object-fit:cover; object-position:center; } .sdn-hero__overlay { background:linear-gradient(90deg,rgba(5,17,39,.97),rgba(7,22,49,.88) 44%,rgba(7,22,49,.2)); } .sdn-hero__content { position:relative; z-index:1; width:min(660px,calc(100% - 380px)); padding:63px; } .sdn-crumbs { display:flex; flex-wrap:wrap; gap:8px; color:rgba(255,255,255,.65); font-size:13px; } .sdn-crumbs a { color:#fff; font-weight:700; } .sdn-hero__flag { display:inline-flex; align-items:center; gap:9px; margin-top:26px; padding:7px 12px; border:1px solid rgba(255,255,255,.24); border-radius:999px; color:#fff; background:rgba(255,255,255,.08); font-size:12px; font-weight:800; backdrop-filter:blur(10px); } .sdn-hero__flag img { width:28px; height:20px; border-radius:3px; object-fit:cover; } .sdn-hero h1 { margin:16px 0 0; color:#fff; font-size:clamp(45px,5.4vw,68px); line-height:1.01; font-weight:800; letter-spacing:-.055em; text-wrap:balance; } .sdn-hero h1 span { color:#ff555e; } .sdn-hero p { max-width:660px; margin:19px 0 0; color:rgba(255,255,255,.83); font-size:17px; line-height:1.72; } .sdn-hero__actions { display:flex; flex-wrap:wrap; gap:13px; margin-top:28px; }
    .sdn-proof { position:relative; z-index:2; display:grid; grid-template-columns:repeat(3,1fr); margin:-1px 28px 0; border:1px solid var(--sdn-line); border-radius:0 0 25px 25px; background:#fff; box-shadow:0 17px 42px rgba(14,33,69,.08); } .sdn-proof__item { display:flex; align-items:center; gap:13px; padding:21px 25px; border-right:1px solid var(--sdn-line); } .sdn-proof__item:last-child { border:0; } .sdn-proof__mark { display:grid; width:38px; height:38px; flex:0 0 38px; place-items:center; border-radius:12px; color:var(--sdn-red); background:#fdebed; font-weight:900; } .sdn-proof strong { display:block; color:var(--sdn-navy); font-size:14px; } .sdn-proof span { display:block; margin-top:3px; color:var(--sdn-muted); font-size:12px; line-height:1.4; } .sdn-proof .sdn-proof__mark { display:grid; margin-top:0; color:var(--sdn-red); } .sdn-proof__mark svg { width:19px; height:19px; fill:none; stroke:currentColor; stroke-linecap:round; stroke-linejoin:round; stroke-width:2.4; }
    .sdn-anchor { position:sticky; z-index:100; top:0; padding:12px 0; border-bottom:1px solid rgba(223,231,240,.9); background:rgba(244,247,251,.94); box-shadow:0 10px 26px rgba(14,33,69,.06); backdrop-filter:blur(16px); } .sdn-anchor__bar { display:flex; gap:8px; overflow-x:auto; padding:7px; border:1px solid var(--sdn-line); border-radius:17px; background:#fff; scrollbar-width:none; } .sdn-anchor__bar::-webkit-scrollbar { display:none; } .sdn-anchor a { flex:0 0 auto; min-height:40px; padding:10px 15px; border-radius:11px; color:#53657f; font-size:13px; font-weight:800; } .sdn-anchor a:first-child,.sdn-anchor a:hover { color:#fff; background:var(--sdn-navy); }
    .sdn-overview { display:grid; grid-template-columns:.95fr 1.05fr; align-items:center; gap:68px; } .sdn-overview__copy p { color:var(--sdn-muted); font-size:16px; line-height:1.82; } .sdn-overview__copy p + p { margin-top:17px; } .sdn-overview__visual { position:relative; min-height:475px; } .sdn-overview__main { position:absolute; inset:0 0 0 54px; overflow:hidden; border-radius:29px; box-shadow:0 22px 52px rgba(14,33,69,.16); } .sdn-overview__main img { width:100%; height:100%; object-fit:cover; } .sdn-overview__badge { position:absolute; bottom:35px; left:0; width:164px; padding:20px 18px; border:7px solid #fff; border-radius:22px; color:#fff; background:var(--sdn-red); box-shadow:0 16px 34px rgba(227,30,36,.22); } .sdn-overview__badge strong { display:block; font-size:23px; line-height:1.1; } .sdn-overview__badge span { display:block; margin-top:7px; font-size:11px; font-weight:700; line-height:1.4; }
    .sdn-awards { display:grid; grid-template-columns:repeat(2,1fr); gap:18px; margin-top:42px; } .sdn-award { min-height:210px; padding:27px; border:1px solid var(--sdn-line); border-radius:22px; background:#fff; box-shadow:0 12px 28px rgba(14,33,69,.05); transition:transform .2s ease,border-color .2s ease,box-shadow .2s ease; } .sdn-award:hover { border-color:rgba(227,30,36,.42); box-shadow:0 18px 38px rgba(14,33,69,.1); transform:translateY(-4px); } .sdn-award__index { display:grid; width:42px; height:42px; place-items:center; border-radius:13px; color:var(--sdn-red); background:#fdebed; font-size:12px; font-weight:900; } .sdn-award h3 { margin:17px 0 0; color:var(--sdn-navy); font-size:19px; line-height:1.3; } .sdn-award p { margin:9px 0 0; color:var(--sdn-muted); font-size:14px; line-height:1.65; }
    .sdn-steps-wrap { padding:56px; background:var(--sdn-navy); background-image:linear-gradient(rgba(255,255,255,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.04) 1px,transparent 1px); background-size:64px 64px; } .sdn-steps-wrap .sdn-kicker { color:#ff7b80; } .sdn-steps-wrap .sdn-title { color:#fff; } .sdn-steps-wrap .sdn-lead { color:rgba(255,255,255,.7); } .sdn-steps { display:grid; grid-template-columns:repeat(3,1fr); gap:18px; margin-top:40px; } .sdn-step { position:relative; min-height:230px; padding:27px; border:1px solid rgba(255,255,255,.15); border-radius:22px; background:rgba(255,255,255,.07); } .sdn-step::after { position:absolute; top:48px; right:-19px; width:20px; border-top:2px dashed rgba(255,255,255,.42); content:''; } .sdn-step:last-child::after { display:none; } .sdn-step__number { display:grid; width:43px; height:43px; place-items:center; border-radius:50%; color:#fff; background:var(--sdn-red); font-size:12px; font-weight:900; } .sdn-step h3 { margin:18px 0 0; color:#fff; font-size:20px; } .sdn-step p { margin:10px 0 0; color:rgba(255,255,255,.68); font-size:14px; line-height:1.68; }
    .sdn-faq-layout { display:grid; grid-template-columns:.72fr 1.28fr; align-items:start; gap:58px; } .sdn-faq-intro { position:sticky; top:100px; } .sdn-faq { display:grid; gap:12px; } .sdn-faq details { overflow:hidden; border:1px solid var(--sdn-line); border-radius:17px; background:#fff; } .sdn-faq summary { position:relative; padding:21px 55px 21px 23px; color:var(--sdn-navy); font-size:16px; font-weight:800; cursor:pointer; list-style:none; } .sdn-faq summary::-webkit-details-marker { display:none; } .sdn-faq summary::after { position:absolute; top:18px; right:22px; color:var(--sdn-red); content:'+'; font-size:25px; font-weight:400; } .sdn-faq details[open] summary::after { content:'−'; } .sdn-faq p { padding:0 23px 22px; color:var(--sdn-muted); line-height:1.72; }
    .sdn-section#enquire { padding-top:56px; padding-bottom:56px; } .sdn-cta { position:relative; overflow:hidden; padding:32px 38px; border-radius:24px; background:var(--sdn-red); box-shadow:0 16px 34px rgba(227,30,36,.16); } .sdn-cta::after { position:absolute; top:-104px; right:-92px; width:280px; height:280px; border:40px solid rgba(255,255,255,.12); border-radius:50%; content:''; } .sdn-cta__content { position:relative; z-index:1; max-width:820px; } .sdn-cta .sdn-kicker { color:rgba(255,255,255,.75); } .sdn-cta h2 { margin:9px 0 0; color:#fff; font-size:clamp(26px,2.7vw,36px); line-height:1.14; font-weight:800; letter-spacing:-.04em; text-wrap:balance; } .sdn-cta p { max-width:730px; margin:10px 0 0; color:rgba(255,255,255,.86); font-size:14px; line-height:1.65; } .sdn-cta .sdn-button { min-height:48px; margin-top:18px; color:var(--sdn-navy)!important; background:#fff; } .sdn-cta .sdn-button:hover { color:var(--sdn-red)!important; }
    /* Compact call-to-action scale used throughout the study-abroad detail pages. */
    .sdn-cta { padding:23px 30px; border-radius:20px; box-shadow:0 13px 28px rgba(227,30,36,.14); }
    .sdn-cta::after { top:-82px; right:-76px; width:210px; height:210px; border-width:30px; }
    .sdn-cta__content { max-width:680px; }
    .sdn-cta h2 { margin-top:7px; font-size:clamp(23px,2.25vw,30px); line-height:1.13; }
    .sdn-cta p { max-width:640px; margin-top:8px; font-size:13px; line-height:1.58; }
    .sdn-cta .sdn-button { min-height:42px; margin-top:14px; padding-inline:18px; }
    @media (max-width:991px) { .sdn-hero { padding-top:105px; } .sdn-overview,.sdn-faq-layout { grid-template-columns:1fr; gap:45px; } .sdn-faq-intro { position:static; } .sdn-overview__visual { max-width:720px; min-height:420px; } .sdn-steps { grid-template-columns:repeat(2,1fr); } .sdn-step:last-child { grid-column:span 2; } .sdn-step:nth-child(2)::after { display:none; } }
    @media (max-width:900px) { .sdn-hero__shell { display:block; min-height:0; } .sdn-hero__content { width:100%; } }
    @media (max-width:767px) { .sdn-page { padding-bottom:76px; } .sdn-wrap { width:min(100% - 28px,620px); } .sdn-section { padding:58px 0; } .sdn-section#enquire { padding-top:42px; padding-bottom:42px; } .sdn-title { font-size:32px; } .sdn-lead { font-size:15px; } .sdn-hero { padding-top:82px; } .sdn-hero__shell { min-height:580px; border-radius:25px; } .sdn-hero__overlay { background:linear-gradient(180deg,rgba(5,17,39,.2),rgba(5,17,39,.97) 72%); } .sdn-hero__content { padding:28px 24px 32px; } .sdn-hero h1 { font-size:42px; } .sdn-hero p { font-size:15px; line-height:1.62; } .sdn-hero__actions { display:grid; grid-template-columns:1fr; } .sdn-button { width:100%; } .sdn-proof { display:flex; overflow-x:auto; margin:0 10px; scroll-snap-type:x mandatory; scrollbar-width:none; } .sdn-proof::-webkit-scrollbar { display:none; } .sdn-proof__item { flex:0 0 83%; border-right:1px solid var(--sdn-line)!important; scroll-snap-align:start; } .sdn-anchor { padding:8px 0; } .sdn-anchor .sdn-wrap { width:100%; } .sdn-anchor__bar { padding-inline:14px; border-inline:0; border-radius:0; } .sdn-overview__visual { min-height:352px; } .sdn-overview__main { inset:0 0 0 28px; border-radius:22px; } .sdn-overview__badge { bottom:17px; width:132px; padding:17px 14px; border-width:5px; border-radius:18px; } .sdn-awards { display:flex; overflow-x:auto; gap:14px; margin-inline:-14px; padding:0 14px 8px; scroll-snap-type:x mandatory; scrollbar-width:none; } .sdn-awards::-webkit-scrollbar { display:none; } .sdn-award { flex:0 0 84%; min-height:195px; scroll-snap-align:start; } .sdn-steps-wrap { padding:42px 14px; } .sdn-steps { display:flex; overflow-x:auto; gap:14px; margin-top:31px; padding:0 2px 8px; scroll-snap-type:x mandatory; scrollbar-width:none; } .sdn-steps::-webkit-scrollbar { display:none; } .sdn-step,.sdn-step:last-child { flex:0 0 84%; min-height:220px; scroll-snap-align:start; } .sdn-step::after { display:none; } .sdn-cta { padding:27px 22px; border-radius:21px; } .sdn-cta h2 { font-size:27px; } .sdn-cta p { font-size:14px; } }
    @media (max-width:767px) { .sdn-cta { padding:22px 20px; border-radius:18px; } .sdn-cta h2 { font-size:24px; } .sdn-cta p { font-size:13px; } }
    @media (prefers-reduced-motion:reduce) { .sdn-page *, .sdn-page *::before,.sdn-page *::after { transition-duration:.01ms!important; scroll-behavior:auto!important; } }
</style>

<main class="sdn-page">
    <section class="sdn-hero" id="overview"><div class="sdn-wrap"><div class="sdn-hero__shell"><img class="sdn-hero__image" src="{{ asset($scholarship['image']) }}" alt="{{ $scholarship['image_alt'] }}" fetchpriority="high" width="1600" height="900"><div class="sdn-hero__overlay"></div><div class="sdn-hero__content"><nav class="sdn-crumbs" aria-label="Breadcrumb"><a href="{{ url('/') }}">Home</a><span>/</span><a href="{{ url('/scholarships') }}">Scholarships</a><span>/</span><span>{{ $scholarship['name'] }}</span></nav><span class="sdn-hero__flag"><img src="{{ asset('assets/transglobe/destinations/flags/'.$scholarship['flag']) }}" alt="{{ $scholarship['name'] }} flag">Scholarships in {{ $scholarship['name'] }}</span><h1>Find your {{ $scholarship['name'] }} <span>funding path.</span></h1><p>{{ $scholarship['tagline'] }}</p><div class="sdn-hero__actions"><a href="{{ url('/#contact') }}" class="sdn-button">Talk to a scholarship expert <span aria-hidden="true">→</span></a><a href="{{ $detailUrl }}#opportunities" class="sdn-button sdn-button--ghost">Explore opportunities</a></div></div>@include('mirror.partials.hero-enquiry', ['formId' => 'scholarship-hero', 'sourceContext' => 'Scholarships — '.$scholarship['name'], 'returnTo' => '/scholarships/'.$scholarship['slug'].'#overview'])</div><div class="sdn-proof"><div class="sdn-proof__item"><span class="sdn-proof__mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m5 12 4.2 4.2L19 6.5"/></svg></span><span><strong>Profile-first matching</strong><span>Funding that suits your plan.</span></span></div><div class="sdn-proof__item"><span class="sdn-proof__mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m5 12 4.2 4.2L19 6.5"/></svg></span><span><strong>Application support</strong><span>Clear, deadline-aware preparation.</span></span></div><div class="sdn-proof__item"><span class="sdn-proof__mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m5 12 4.2 4.2L19 6.5"/></svg></span><span><strong>Realistic guidance</strong><span>Know the value and conditions.</span></span></div></div></div></section>
    <nav class="sdn-anchor" aria-label="Scholarship page sections"><div class="sdn-wrap"><div class="sdn-anchor__bar"><a href="{{ $detailUrl }}#overview">Overview</a><a href="{{ $detailUrl }}#gallery">In focus</a><a href="{{ $detailUrl }}#opportunities">Opportunities</a><a href="{{ $detailUrl }}#process">How we help</a><a href="{{ $detailUrl }}#universities">Universities</a><a href="{{ $detailUrl }}#faqs">FAQs</a><a href="{{ $detailUrl }}#enquire">Enquire</a></div></div></nav>
    <section class="sdn-section"><div class="sdn-wrap sdn-overview"><div class="sdn-overview__copy"><div class="sdn-kicker">Scholarships in {{ $scholarship['name'] }}</div><h2 class="sdn-title">Make a more affordable international education plan.</h2><p>{{ $scholarship['intro'] }}</p><p>Scholarships are competitive and conditions can change, so we focus on well-matched opportunities and a strong, timely application.</p><a href="{{ $detailUrl }}#opportunities" class="sdn-button" style="margin-top:26px">See scholarship opportunities</a></div><div class="sdn-overview__visual"><div class="sdn-overview__main"><img src="{{ asset($scholarship['image']) }}" alt="{{ $scholarship['image_alt'] }}" loading="lazy" width="1200" height="800"></div><div class="sdn-overview__badge"><strong>{{ count($scholarship['awards']) }} routes</strong><span>Explore recognised funding paths for eligible students</span></div></div></div></section>
    <x-detail-media-gallery :images="$scholarshipMedia" id="gallery" eyebrow="{{ $scholarship['name'] }} in focus" title="See the study environment behind your funding plan." lead="Scholarship applications are strongest when the award, university and course all fit the destination you are choosing." />
    <section class="sdn-section sdn-section--soft" id="opportunities"><div class="sdn-wrap"><div class="sdn-center"><div class="sdn-kicker">Funding opportunities</div><h2 class="sdn-title">Scholarship routes to explore in {{ $scholarship['name'] }}.</h2><p class="sdn-lead">These are examples to help you understand the funding landscape. Eligibility, value and availability must always be checked for your course and intake.</p></div><div class="sdn-awards">@foreach($scholarship['awards'] as $index => [$title, $copy])<article class="sdn-award"><span class="sdn-award__index">{{ str_pad($index+1,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $title }}</h3><p>{{ $copy }}</p></article>@endforeach</div></div></section>
    <section class="sdn-section sdn-steps-wrap" id="process"><div class="sdn-wrap"><div class="sdn-center"><div class="sdn-kicker">How we help</div><h2 class="sdn-title">A better way to approach scholarship applications.</h2><p class="sdn-lead">We keep the process specific to you—from your current profile to the evidence and deadline behind each application.</p></div><div class="sdn-steps">@foreach($scholarship['steps'] as $index => [$title, $copy])<article class="sdn-step"><span class="sdn-step__number">{{ str_pad($index+1,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $title }}</h3><p>{{ $copy }}</p></article>@endforeach</div></div></section>
    <section class="sdn-section" id="universities"><div class="sdn-wrap"><div class="sdn-center"><div class="sdn-kicker">University network</div><h2 class="sdn-title">Explore institutions in {{ $scholarship['name'] }}.</h2><p class="sdn-lead">Country-specific university options from the Trans Globe destination network, where scholarships and entry conditions can be checked against your profile.</p></div><x-university-network :universities="$scholarshipUniversities" :country="$scholarship['name']" slug="scholarship-{{ $scholarship['slug'] }}" /></div></section>
    <section class="sdn-section" id="faqs"><div class="sdn-wrap sdn-faq-layout"><div class="sdn-faq-intro"><div class="sdn-kicker">Frequently asked questions</div><h2 class="sdn-title">Answers before you apply.</h2><p class="sdn-lead">A scholarship conversation can help you prioritise your applications and avoid missing crucial deadlines.</p><a href="{{ url('/#contact') }}" class="sdn-button" style="margin-top:25px">Speak to an expert</a></div><div class="sdn-faq">@foreach($scholarship['faqs'] as [$question,$answer])<details><summary>{{ $question }}</summary><p>{{ $answer }}</p></details>@endforeach</div></div></section>
    <section class="sdn-section sdn-section--soft" id="enquire"><div class="sdn-wrap"><div class="sdn-cta"><div class="sdn-cta__content"><div class="sdn-kicker">Start with your profile</div><h2>Let’s find the scholarships your plan could unlock.</h2><p>Share your academic profile, course preference and destination ideas. Our team will help you take the most practical next step.</p><a href="{{ url('/#contact') }}" class="sdn-button">Book my free scholarship counselling <span aria-hidden="true">→</span></a></div></div></div></section>
</main>

@include('mirror.partials.footer')
