@include('mirror.partials.header')
@include('mirror.partials.mobile-destination-nav')

@php
    $title = $cms['hero_title'] ?? $event['title'];
    $summary = $cms['hero_copy'] ?? $event['summary'];
    $image = $cms['hero_image'] ?? $event['image'];
    $overview = $cms['overview_copy'] ?? $event['overview'];
    $isUpcoming = $event['status'] === 'Upcoming';
@endphp

<style>
@font-face{font-family:'Plus Jakarta Sans';src:url('{{ asset('assets/fonts/plus-jakarta-sans-latin.woff2') }}') format('woff2');font-style:normal;font-weight:200 800;font-display:swap}
.ed-page{--navy:#0e2145;--red:#e31e24;--orange:#f3951e;--soft:#f3f7fb;--line:#dfe7f1;color:var(--navy);font-family:'Plus Jakarta Sans',sans-serif;background:#fff}.ed-page *{box-sizing:border-box}.ed-wrap{width:min(1140px,calc(100% - 40px));margin:auto}.ed-hero{padding:28px 0 0;background:var(--soft)}
.ed-hero__panel{min-height:570px;border-radius:34px;overflow:hidden;position:relative;display:flex;align-items:flex-end;background:center/cover no-repeat;box-shadow:0 22px 55px rgba(14,33,69,.16)}.ed-hero__panel:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(4,16,42,.96),rgba(4,16,42,.62) 58%,rgba(4,16,42,.18))}.ed-hero__content{position:relative;z-index:1;width:min(760px,100%);padding:58px;color:#fff}.ed-breadcrumb{display:flex;gap:9px;align-items:center;font-size:13px;color:rgba(255,255,255,.7);margin-bottom:28px}.ed-breadcrumb a{color:#fff}.ed-pill{display:inline-flex;align-items:center;gap:8px;padding:9px 13px;border-radius:999px;background:var(--red);font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.ed-hero h1{font-size:clamp(42px,6vw,74px);line-height:1.02;letter-spacing:-.045em;color:#fff;margin:18px 0}.ed-hero p{font-size:17px;line-height:1.75;color:rgba(255,255,255,.8);max-width:650px}.ed-button{display:inline-flex;align-items:center;justify-content:center;gap:10px;min-height:52px;padding:0 24px;border-radius:13px;background:var(--red);color:#fff!important;font-weight:800;text-decoration:none;border:0;transition:.2s ease}.ed-button:hover,.ed-button:focus-visible{background:var(--orange);transform:translateY(-2px)}
.ed-facts{position:relative;z-index:2;margin-top:-28px}.ed-facts__grid{display:grid;grid-template-columns:repeat(4,1fr);border-radius:22px;background:#fff;border:1px solid var(--line);box-shadow:0 14px 40px rgba(14,33,69,.1);overflow:hidden}.ed-fact{padding:24px;border-right:1px solid var(--line)}.ed-fact:last-child{border:0}.ed-fact small{display:block;color:#7b8ba7;text-transform:uppercase;letter-spacing:.09em;font-size:10px;font-weight:800;margin-bottom:7px}.ed-fact strong{font-size:16px}.ed-tabs{position:sticky;top:0;z-index:20;background:rgba(255,255,255,.94);backdrop-filter:blur(14px);border-bottom:1px solid var(--line);margin-top:28px}.ed-tabs__inner{display:flex;gap:30px;overflow-x:auto;scrollbar-width:none}.ed-tabs a{padding:18px 0;color:#53627d;font-size:13px;font-weight:800;white-space:nowrap;text-decoration:none;border-bottom:2px solid transparent}.ed-tabs a:hover,.ed-tabs a:focus-visible{color:var(--orange);border-color:var(--orange)}
.ed-section{padding:90px 0}.ed-section--soft{background:var(--soft)}.ed-kicker{display:flex;align-items:center;gap:10px;color:var(--red);font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.ed-kicker:before{content:'';width:28px;height:2px;background:currentColor}.ed-title{font-size:clamp(32px,4vw,50px);line-height:1.08;letter-spacing:-.04em;margin:14px 0 18px}.ed-lead{font-size:17px;line-height:1.85;color:#61718d}.ed-overview{display:grid;grid-template-columns:.9fr 1.1fr;gap:60px;align-items:center}.ed-overview__image{height:500px;border-radius:28px;overflow:hidden;position:relative}.ed-overview__image img{width:100%;height:100%;object-fit:cover}.ed-overview__stamp{position:absolute;left:20px;bottom:20px;background:#fff;border-radius:16px;padding:16px 18px;font-weight:800;box-shadow:0 10px 25px rgba(14,33,69,.18)}.ed-highlights{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:30px}.ed-highlight{background:#fff;border:1px solid var(--line);padding:24px;border-radius:20px}.ed-highlight__number{width:42px;height:42px;display:grid;place-items:center;border-radius:13px;background:#fff0f0;color:var(--red);font-weight:800}.ed-highlight h3{font-size:18px;margin:18px 0 0;line-height:1.4}
.ed-flow{margin-top:40px;display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.ed-step{position:relative;padding:28px 22px;border-radius:20px;background:#192e55;color:#fff;border:1px solid rgba(255,255,255,.12)}.ed-step:not(:last-child):after{content:'→';position:absolute;right:-22px;top:50%;z-index:2;color:var(--red);font-size:24px;font-weight:800}.ed-step__num{display:grid;place-items:center;width:42px;height:42px;border-radius:50%;background:var(--red);font-size:12px;font-weight:800}.ed-step h3{color:#fff;font-size:17px;margin:18px 0 8px}.ed-step p{color:rgba(255,255,255,.68);font-size:13px;line-height:1.65;margin:0}.ed-dark{background:var(--navy);color:#fff}.ed-dark .ed-title{color:#fff}.ed-dark .ed-lead{color:rgba(255,255,255,.7)}
.ed-faq{max-width:880px;margin:35px auto 0}.ed-faq details{border-bottom:1px solid var(--line);padding:20px 0}.ed-faq summary{cursor:pointer;list-style:none;font-weight:800;display:flex;justify-content:space-between;gap:20px}.ed-faq summary:after{content:'+';color:var(--red);font-size:22px}.ed-faq details[open] summary:after{content:'−'}.ed-faq p{color:#657590;line-height:1.75;margin:15px 0 0}.ed-cta{display:grid;grid-template-columns:1fr .95fr;background:var(--navy);border-radius:30px;overflow:hidden;color:#fff}.ed-cta__copy{padding:48px}.ed-cta h2{color:#fff;font-size:clamp(32px,4vw,48px);line-height:1.1;margin:14px 0}.ed-cta p{color:rgba(255,255,255,.7);line-height:1.7}.ed-cta__image{min-height:380px}.ed-cta__image img{width:100%;height:100%;object-fit:cover}
@media(max-width:991px){.ed-overview,.ed-cta{grid-template-columns:1fr}.ed-facts__grid{grid-template-columns:repeat(2,1fr)}.ed-fact:nth-child(2){border-right:0}.ed-fact:nth-child(-n+2){border-bottom:1px solid var(--line)}.ed-flow{grid-template-columns:repeat(2,1fr)}.ed-step:not(:last-child):after{display:none}}
@media(max-width:767px){.ed-wrap{width:min(100% - 24px,1140px)}.ed-hero{padding:12px 0 0}.ed-hero__panel{min-height:610px;border-radius:26px}.ed-hero__panel:after{background:linear-gradient(0deg,rgba(4,16,42,.96),rgba(4,16,42,.38))}.ed-hero__content{padding:28px}.ed-hero h1{font-size:42px}.ed-hero p{font-size:15px}.ed-facts__grid{grid-template-columns:1fr 1fr}.ed-fact{padding:18px}.ed-section{padding:64px 0}.ed-overview{gap:30px}.ed-overview__image{height:360px}.ed-highlights{display:flex;overflow-x:auto;scroll-snap-type:x mandatory}.ed-highlight{min-width:82vw;scroll-snap-align:start}.ed-flow{display:flex;overflow-x:auto;scroll-snap-type:x mandatory}.ed-step{min-width:82vw;scroll-snap-align:start}.ed-cta__copy{padding:30px}.ed-cta__image{min-height:270px}.ed-button{width:100%}}
@media(prefers-reduced-motion:reduce){.ed-page *{scroll-behavior:auto!important;transition:none!important}.ed-button:hover{transform:none}}
</style>

<main class="ed-page">
    <section class="ed-hero"><div class="ed-wrap"><div class="ed-hero__panel" style="background-image:url('{{ asset($image) }}')"><div class="ed-hero__content"><nav class="ed-breadcrumb" aria-label="Breadcrumb"><a href="{{ url('/') }}">Home</a><span>/</span><a href="{{ url('/events') }}">Events</a><span>/</span><span>{{ $event['destination'] }}</span></nav><span class="ed-pill">{{ $event['status'] }}</span><h1>{{ $title }}</h1><p>{{ $summary }}</p><a href="#enquire" class="ed-button">{{ $isUpcoming ? 'Register my interest' : 'Plan my next event' }} <span aria-hidden="true">→</span></a></div></div></div></section>
    <section class="ed-facts"><div class="ed-wrap"><div class="ed-facts__grid"><div class="ed-fact"><small>Date</small><strong>{{ $event['date'] }}</strong></div><div class="ed-fact"><small>Time</small><strong>{{ $event['time'] }}</strong></div><div class="ed-fact"><small>Destination</small><strong>{{ $event['destination'] }}</strong></div><div class="ed-fact"><small>Guidance team</small><strong>{{ $event['location'] }}</strong></div></div></div></section>
    <nav class="ed-tabs" aria-label="Event page sections"><div class="ed-wrap ed-tabs__inner"><a href="#overview">Overview</a><a href="#highlights">What you will explore</a><a href="#journey">How it works</a><a href="#faqs">FAQs</a><a href="#enquire">Enquire</a></div></nav>

    <section class="ed-section" id="overview"><div class="ed-wrap"><div class="ed-overview"><div class="ed-overview__image"><img src="{{ asset($image) }}" alt="{{ $event['image_alt'] }}"><span class="ed-overview__stamp">{{ $event['date'] }}</span></div><div><span class="ed-kicker">About this event</span><h2 class="ed-title">A useful conversation before a big decision.</h2><p class="ed-lead">{{ $overview }}</p><p class="ed-lead">Contact our Indore team for the latest attendance mode, venue information and availability.</p></div></div></div></section>

    <section class="ed-section ed-section--soft" id="highlights"><div class="ed-wrap"><span class="ed-kicker">What you will explore</span><h2 class="ed-title">Arrive with questions. Leave with direction.</h2><div class="ed-highlights">@foreach($event['highlights'] as $index => $highlight)<article class="ed-highlight"><span class="ed-highlight__number">0{{ $index + 1 }}</span><h3>{{ $highlight }}</h3></article>@endforeach</div></div></section>

    <section class="ed-section ed-dark" id="journey"><div class="ed-wrap"><span class="ed-kicker">Your connected event journey</span><h2 class="ed-title">Four simple steps from interest to action.</h2><p class="ed-lead">The event is one part of your plan. Our Indore team helps connect the information to your profile and next application milestone.</p><div class="ed-flow">@foreach($event['steps'] as $index => $step)<article class="ed-step"><span class="ed-step__num">0{{ $index + 1 }}</span><h3>{{ $step[0] }}</h3><p>{{ $step[1] }}</p></article>@endforeach</div></div></section>

    <section class="ed-section" id="faqs"><div class="ed-wrap"><div style="text-align:center"><span class="ed-kicker" style="justify-content:center">Questions answered</span><h2 class="ed-title">Before you attend</h2></div><div class="ed-faq">@foreach($event['faqs'] as $faq)<details><summary>{{ $faq[0] }}</summary><p>{{ $faq[1] }}</p></details>@endforeach</div></div></section>

    <section class="ed-section ed-section--soft" id="enquire"><div class="ed-wrap"><div class="ed-cta"><div class="ed-cta__copy"><span class="ed-kicker">Speak to Trans Globe Indore</span><h2>{{ $isUpcoming ? 'Confirm your interest in this event.' : 'Be ready for the next university conversation.' }}</h2><p>Share your destination, study level and preferred intake. We will help you understand the right next step and confirm current event availability.</p><a class="ed-button" href="{{ url('/contact#enquiry') }}">Send my enquiry <span aria-hidden="true">→</span></a></div><div class="ed-cta__image"><img src="{{ asset($image) }}" alt="{{ $event['image_alt'] }}"></div></div></div></section>
</main>

@include('mirror.partials.footer')
