import {
  PlusJakartaSans_400Regular,
  PlusJakartaSans_600SemiBold,
  PlusJakartaSans_700Bold,
  PlusJakartaSans_800ExtraBold,
  useFonts,
} from '@expo-google-fonts/plus-jakarta-sans';
import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { StatusBar } from 'expo-status-bar';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, ImageBackground, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { askStudyAssistant, evaluateProfile, loadCatalog, submitEnquiry } from './src/api';
import type { AppTab, ChatMessage, Destination, EvaluationResult, MobileCatalog } from './src/models';

const p = { navy: '#0F172A', slate: '#334155', muted: '#64748B', line: '#E2E8F0', canvas: '#F8FAFC', white: '#FFFFFF', red: '#DC2626', amber: '#F59E0B', emerald: '#059669', redSoft: '#FEF2F2' };
const font = { regular: 'PlusJakartaSans_400Regular', semi: 'PlusJakartaSans_600SemiBold', bold: 'PlusJakartaSans_700Bold', extra: 'PlusJakartaSans_800ExtraBold' };

type IconName = React.ComponentProps<typeof MaterialCommunityIcons>['name'];
function Icon({ name, color = p.slate, size = 20 }: { name: IconName; color?: string; size?: number }) { return <MaterialCommunityIcons name={name} color={color} size={size} />; }
function T({ children, style, numberOfLines }: { children: React.ReactNode; style?: object; numberOfLines?: number }) { return <Text numberOfLines={numberOfLines} style={[s.text, style]}>{children}</Text>; }
function valueOf(items: string[][], index: number, fallback: string) { return items[index]?.[1] ?? items[index]?.[0] ?? fallback; }
function Chip({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[s.chip, selected && s.chipOn]}><T style={[s.chipText, selected && s.chipTextOn]}>{label}</T></Pressable>; }

function Header({ onBook, onRefresh, loading }: { onBook: () => void; onRefresh: () => void; loading: boolean }) {
  return <View style={s.header}><View style={s.brandRow}><View style={s.brandMark}><T style={s.brandMarkText}>TG</T></View><View><View style={s.brandTitleRow}><T style={s.brandTitle}>Trans Globe</T><T style={s.indore}>INDORE</T></View><View style={s.location}><Icon name="map-marker" color={p.red} size={12} /><T style={s.locationText}>Indore, Madhya Pradesh</T></View></View></View><View style={s.headerButtons}><Pressable accessibilityLabel="Refresh GEIC catalogue" onPress={onRefresh} style={s.headerButton}>{loading ? <ActivityIndicator size="small" color={p.slate} /> : <Icon name="refresh" size={18} />}</Pressable><Pressable accessibilityLabel="Book free counselling" onPress={onBook} style={[s.headerButton, s.headerBook]}><Icon name="calendar-check" color={p.red} size={18} /></Pressable></View></View>;
}

function Title({ eyebrow, title, action, onAction }: { eyebrow?: string; title: string; action?: string; onAction?: () => void }) {
  return <View style={s.titleRow}><View style={{ flex: 1 }}>{eyebrow ? <T style={s.eyebrow}>{eyebrow}</T> : null}<T style={s.heading}>{title}</T></View>{action ? <Pressable onPress={onAction} style={s.titleAction}><T style={s.titleActionText}>{action}</T><Icon name="chevron-right" color={p.red} size={17} /></Pressable> : null}</View>;
}

function DestinationCard({ item, onPress }: { item: Destination; onPress: () => void }) {
  return <Pressable onPress={onPress} style={s.destinationCard}><Image source={{ uri: item.imageUrl }} style={s.destinationImage} /><View style={s.destinationBody}><T style={s.destinationName}>{item.name}</T><T numberOfLines={2} style={s.destinationTagline}>{item.tagline}</T><View style={s.destinationMeta}><T style={s.destinationMetaText}>{valueOf(item.costs, 0, 'Plan costs')}</T><Icon name="arrow-top-right" color={p.red} size={16} /></View></View></Pressable>;
}

function Hero({ item, onOpen, onBook }: { item: Destination; onOpen: () => void; onBook: () => void }) {
  return <ImageBackground source={{ uri: item.imageUrl }} imageStyle={s.heroImage} style={s.hero}><View style={s.overlay} /><View style={s.heroContent}><View style={s.heroBadges}><T style={s.heroBadge}>{item.stat}</T><T style={s.heroBadge}>GEIC GUIDE</T></View><View><T style={s.heroEyebrow}>STUDY DESTINATION</T><T style={s.heroTitle}>{item.name}</T><T style={s.heroCopy}>{item.tagline}</T><View style={s.heroActions}><Pressable onPress={onBook} style={s.heroPrimary}><T style={s.heroPrimaryText}>Free 1-on-1 session</T></Pressable><Pressable onPress={onOpen} style={s.heroSecondary}><T style={s.heroSecondaryText}>Explore</T><Icon name="arrow-right" color={p.white} size={15} /></Pressable></View></View></View></ImageBackground>;
}

function HomeTab({ catalog, onTab, onDestination, onBook }: { catalog: MobileCatalog; onTab: (tab: AppTab) => void; onDestination: (item: Destination) => void; onBook: () => void }) {
  const featured = catalog.destinations[0];
  const event = catalog.events[0];
  const quickActions: Array<[string, IconName, () => void]> = [
    ['Explore countries', 'earth', () => onTab('explore')], ['AI advisor', 'message-text-outline', () => onTab('advisor')], ['Profile evaluator', 'shield-check-outline', () => onTab('evaluate')], ['Free counselling', 'calendar-check-outline', onBook],
  ];
  return <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
    {featured ? <Hero item={featured} onOpen={() => onDestination(featured)} onBook={onBook} /> : null}
    {event ? <Pressable onPress={onBook} style={s.expoCard}><View style={s.expoGlow} /><T style={s.expoKicker}>{event.type || 'MAJOR INDORE EVENT'}</T><T style={s.expoTitle}>{event.title}</T><T style={s.expoCopy}>{event.date} · {event.location}</T><View style={s.expoFooter}><T style={s.expoAction}>Book your place</T><Icon name="arrow-right" color="#FDE68A" size={17} /></View></Pressable> : null}
    <Title eyebrow="START HERE" title="Build your global study plan" />
    <View style={s.quickGrid}>{quickActions.map(([label, icon, action]) => <Pressable key={label} onPress={action} style={s.quickCard}><View style={s.quickIcon}><Icon name={icon} color={p.red} size={22} /></View><T style={s.quickTitle}>{label}</T><Icon name="arrow-top-right" color={p.muted} size={17} /></Pressable>)}</View>
    <View style={s.statPanel}>{[['70K+', 'Students'], ['800+', 'Universities'], ['98.7%', 'Visa rate'], ['34+', 'Years']].map(([number, label]) => <View key={label} style={s.statCell}><T style={s.statValue}>{number}</T><T style={s.statLabel}>{label}</T></View>)}</View>
    <Title eyebrow="EXPLORE" title="Trending study destinations" action="View all" onAction={() => onTab('explore')} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}>{catalog.destinations.map((item) => <DestinationCard key={item.id} item={item} onPress={() => onDestination(item)} />)}</ScrollView>
    <Title eyebrow="OUR APPROACH" title="Four simple milestones" />
    <View style={s.roadmap}>{[['01', 'Discover', 'Clarify course, country, budget and career direction.'], ['02', 'Shortlist', 'Compare official requirements, costs and course fit.'], ['03', 'Apply', 'Prepare documents and complete applications.'], ['04', 'Prepare', 'Review your offer, visa evidence and departure plan.']].map(([number, title, copy]) => <View key={number} style={s.roadmapRow}><View style={s.step}><T style={s.stepText}>{number}</T></View><View style={{ flex: 1 }}><T style={s.roadmapTitle}>{title}</T><T style={s.roadmapCopy}>{copy}</T></View></View>)}</View>
  </ScrollView>;
}

function ExploreTab({ catalog, onDestination }: { catalog: MobileCatalog; onDestination: (item: Destination) => void }) {
  const [query, setQuery] = useState('');
  const [section, setSection] = useState<'destinations' | 'services'>('destinations');
  const destinations = catalog.destinations.filter((item) => `${item.name} ${item.tagline} ${item.highlights.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const services = catalog.services.filter((item) => `${item.title} ${item.description}`.toLowerCase().includes(query.toLowerCase()));
  return <ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled"><Title eyebrow="EXPLORE" title="Find the right route" /><View style={s.search}><Icon name="magnify" color={p.muted} size={19} /><TextInput value={query} onChangeText={setQuery} placeholder="Search destination or service" placeholderTextColor={p.muted} style={s.searchInput} /></View><View style={s.segmented}>{(['destinations', 'services'] as const).map((item) => <Pressable key={item} onPress={() => setSection(item)} style={[s.segment, section === item && s.segmentOn]}><T style={[s.segmentText, section === item && s.segmentTextOn]}>{item === 'destinations' ? `Destinations (${catalog.destinations.length})` : `Services (${catalog.services.length})`}</T></Pressable>)}</View>{section === 'destinations' ? <View style={s.list}>{destinations.map((item) => <Pressable key={item.id} onPress={() => onDestination(item)} style={s.listCard}><Image source={{ uri: item.imageUrl }} style={s.listImage} /><View style={{ flex: 1 }}><T style={s.listTitle}>{item.name}</T><T numberOfLines={2} style={s.listCopy}>{item.tagline}</T><T style={s.listTag}>{item.stat}</T></View><Icon name="chevron-right" color={p.red} size={22} /></Pressable>)}</View> : <View style={s.list}>{services.map((item, index) => <View key={item.id} style={s.serviceCard}><View style={s.serviceIcon}><Icon name="briefcase-outline" color={p.red} size={23} /></View><View style={{ flex: 1 }}><T style={s.serviceIndex}>0{index + 1}</T><T style={s.listTitle}>{item.title}</T><T style={s.listCopy}>{item.description}</T></View></View>)}</View>}</ScrollView>;
}

function AdvisorTab({ onBook }: { onBook: () => void }) {
  const [messages, setMessages] = useState<ChatMessage[]>([{ id: 'welcome', role: 'assistant', content: 'Hi! I’m the Trans Globe Study Assistant. Share your preferred destination, course level, academic result or intake and I’ll help you find a useful starting point.' }]);
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);
  async function send(value = message) {
    const question = value.trim();
    if (!question || loading) return;
    setMessages((current) => [...current, { id: `user-${Date.now()}`, role: 'user', content: question }]);
    setMessage(''); setLoading(true);
    try { const reply = await askStudyAssistant(question, messages); setMessages((current) => [...current, { id: `assistant-${Date.now()}`, role: 'assistant', content: reply }]); }
    catch (error) { setMessages((current) => [...current, { id: `error-${Date.now()}`, role: 'assistant', content: error instanceof Error ? error.message : 'The advisor is unavailable. Please try again.' }]); }
    finally { setLoading(false); }
  }
  return <View style={s.advisorPage}><View style={s.advisorHeader}><View style={s.advisorBot}><Icon name="robot-outline" color={p.white} size={23} /></View><View style={{ flex: 1 }}><T style={s.advisorTitle}>Trans Globe Advisor</T><T style={s.advisorSub}>Grounded in the current GEIC catalogue</T></View><Pressable onPress={onBook} style={s.advisorBook}><T style={s.advisorBookText}>Book call</T></Pressable></View><ScrollView contentContainerStyle={s.chatList}>{messages.map((item) => <View key={item.id} style={[s.messageRow, item.role === 'user' && s.messageRowUser]}><View style={[s.avatar, item.role === 'user' ? s.userAvatar : s.botAvatar]}><Icon name={item.role === 'user' ? 'account' : 'robot-outline'} color={p.white} size={15} /></View><View style={[s.bubble, item.role === 'user' ? s.userBubble : s.botBubble]}><T style={[s.messageText, item.role === 'user' && s.userText]}>{item.content}</T></View></View>)}{loading ? <View style={s.loadingReply}><ActivityIndicator color={p.red} /><T style={s.loadingReplyText}>Consulting the GEIC knowledge base…</T></View> : null}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.prompts}>{['Compare Australia and the UK', 'Which test should I take?', 'Build my study plan'].map((prompt) => <Pressable key={prompt} onPress={() => void send(prompt)} style={s.prompt}><T style={s.promptText}>{prompt}</T></Pressable>)}</ScrollView><View style={s.composer}><TextInput value={message} onChangeText={setMessage} onSubmitEditing={() => void send()} placeholder="Ask about courses, tests or applications" placeholderTextColor={p.muted} style={s.composerInput} /><Pressable onPress={() => void send()} disabled={!message.trim() || loading} style={[s.send, (!message.trim() || loading) && s.sendOff]}><Icon name="send" color={p.white} size={20} /></Pressable></View></View>;
}

function EvaluateTab({ catalog, onBook }: { catalog: MobileCatalog; onBook: (destination?: string) => void }) {
  const [score, setScore] = useState('76');
  const [level, setLevel] = useState('Postgraduate');
  const [destinations, setDestinations] = useState<string[]>(catalog.destinations.slice(0, 2).map((item) => item.name));
  const [test, setTest] = useState('IELTS');
  const [testScore, setTestScore] = useState('6.5');
  const [result, setResult] = useState<EvaluationResult | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  function toggleDestination(name: string) { setDestinations((current) => current.includes(name) ? current.length > 1 ? current.filter((item) => item !== name) : current : current.length < 3 ? [...current, name] : current); }
  async function evaluate() {
    const academicPercentage = Number(score);
    if (!Number.isFinite(academicPercentage) || academicPercentage < 35 || academicPercentage > 100) { setError('Enter an academic percentage between 35 and 100.'); return; }
    setError(''); setLoading(true);
    try { setResult(await evaluateProfile({ academicPercentage, studyLevel: level, preferredDestinations: destinations, englishTest: test, englishScore: testScore })); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'Evaluation is unavailable.'); }
    finally { setLoading(false); }
  }
  return <ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled"><Title eyebrow="INSTANT PLANNING TOOL" title="Profile evaluator & readiness meter" /><View style={s.formCard}><T style={s.fieldLabel}>Academic percentage</T><TextInput value={score} onChangeText={setScore} keyboardType="decimal-pad" style={s.field} placeholder="76" /><T style={s.fieldLabel}>Study level</T><View style={s.chipWrap}>{['Undergraduate', 'Postgraduate', 'Diploma or pathway', 'Research'].map((item) => <Chip key={item} label={item} selected={level === item} onPress={() => setLevel(item)} />)}</View><T style={s.fieldLabel}>Preferred destinations (up to 3)</T><View style={s.chipWrap}>{catalog.destinations.map((item) => <Chip key={item.id} label={item.name} selected={destinations.includes(item.name)} onPress={() => toggleDestination(item.name)} />)}</View><T style={s.fieldLabel}>English test</T><View style={s.chipWrap}>{['IELTS', 'PTE', 'TOEFL', 'Duolingo', 'Planning to take a test'].map((item) => <Chip key={item} label={item} selected={test === item} onPress={() => setTest(item)} />)}</View><T style={s.fieldLabel}>Current or target score</T><TextInput value={testScore} onChangeText={setTestScore} style={s.field} placeholder="6.5" />{error ? <T style={s.error}>{error}</T> : null}<Pressable onPress={() => void evaluate()} style={s.primary}>{loading ? <ActivityIndicator color={p.white} /> : <><Icon name="shield-check-outline" color={p.white} size={19} /><T style={s.primaryText}>Evaluate my profile</T></>}</Pressable></View>{result ? <View style={s.result}><View style={s.score}><T style={s.scoreValue}>{result.readinessScore}</T><T style={s.scoreLabel}>READINESS</T></View><T style={s.resultTitle}>Your planning snapshot</T><T style={s.resultCopy}>{result.summary}</T><T style={s.resultHeading}>DESTINATION FIT</T>{result.matches.map((match) => <View key={match.id} style={s.match}><View style={s.matchIcon}><Icon name="map-marker-outline" color={p.red} size={18} /></View><View style={{ flex: 1 }}><T style={s.matchName}>{match.name}</T><T style={s.matchCopy}>{match.fit} · {match.nextIntake}</T></View></View>)}<T style={s.resultHeading}>NEXT STEPS</T>{result.actionItems.map((item) => <View key={item} style={s.bullet}><Icon name="check-circle" color={p.emerald} size={17} /><T style={s.bulletText}>{item}</T></View>)}<T style={s.disclaimer}>{result.disclaimer}</T><Pressable onPress={() => onBook(destinations[0])} style={s.primary}><T style={s.primaryText}>Discuss with an Indore specialist</T><Icon name="arrow-right" color={p.white} size={18} /></Pressable></View> : null}</ScrollView>;
}

function MoreTab({ catalog, onBook }: { catalog: MobileCatalog; onBook: () => void }) {
  const [section, setSection] = useState<'services' | 'events' | 'tests'>('services');
  const content = section === 'services' ? catalog.services : section === 'events' ? catalog.events : catalog.tests;
  return <ScrollView contentContainerStyle={s.scroll}><Title eyebrow="MORE FROM GEIC" title="Services, events and test preparation" /><View style={s.segmented}>{(['services', 'events', 'tests'] as const).map((item) => <Pressable key={item} onPress={() => setSection(item)} style={[s.segment, section === item && s.segmentOn]}><T style={[s.segmentText, section === item && s.segmentTextOn]}>{item[0].toUpperCase() + item.slice(1)}</T></Pressable>)}</View><View style={s.list}>{content.map((item) => <View key={item.id} style={s.moreCard}><Image source={{ uri: item.imageUrl }} style={s.moreImage} /><View style={{ flex: 1 }}><T style={s.listTitle}>{item.title}</T><T numberOfLines={3} style={s.listCopy}>{item.description}</T><Pressable onPress={onBook} style={s.moreAction}><T style={s.moreActionText}>Talk to an expert</T><Icon name="arrow-right" color={p.red} size={16} /></Pressable></View></View>)}</View><View style={s.contactCard}><Icon name="map-marker-outline" color={p.red} size={25} /><View style={{ flex: 1 }}><T style={s.contactTitle}>{catalog.contact.office}</T><T style={s.contactCopy}>{catalog.contact.email}</T></View><Pressable onPress={onBook} style={s.contactButton}><T style={s.contactButtonText}>Book</T></Pressable></View></ScrollView>;
}

function Nav({ active, onChange }: { active: AppTab; onChange: (tab: AppTab) => void }) {
  const tabs: Array<[AppTab, string, IconName]> = [['home', 'Home', 'home-variant-outline'], ['explore', 'Explore', 'compass-outline'], ['advisor', 'AI Advisor', 'message-text-outline'], ['evaluate', 'Evaluate', 'shield-check-outline'], ['more', 'More', 'view-grid-outline']];
  return <View style={s.navWrap}><View style={s.nav}>{tabs.map(([key, label, icon]) => <Pressable key={key} onPress={() => onChange(key)} style={[s.navItem, key === 'advisor' && s.navAdvisor]}><View style={[s.navIcon, active === key && s.navIconOn, key === 'advisor' && s.navIconAdvisor]}><Icon name={icon} color={active === key || key === 'advisor' ? p.white : '#94A3B8'} size={20} /></View><T style={[s.navLabel, active === key && s.navLabelOn]}>{label}</T></Pressable>)}</View></View>;
}

function DestinationSheet({ item, onClose, onBook }: { item: Destination | null; onClose: () => void; onBook: (destination?: string) => void }) {
  if (!item) return null;
  return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={s.sheet}><ImageBackground source={{ uri: item.imageUrl }} style={s.sheetHero}><View style={s.overlay} /><View style={s.sheetTop}><T style={s.sheetBadge}>{item.stat}</T><Pressable onPress={onClose} style={s.close}><Icon name="close" color={p.white} size={21} /></Pressable></View><View style={s.sheetHeroCopy}><T style={s.sheetTitle}>{item.name}</T><T style={s.sheetTagline}>{item.tagline}</T></View></ImageBackground><ScrollView contentContainerStyle={s.sheetContent}><T style={s.sheetHeading}>Why choose {item.name}</T><T style={s.sheetCopy}>{item.detail}</T>{item.highlights.map((detail) => <View key={detail} style={s.bullet}><Icon name="check-circle" color={p.red} size={17} /><T style={s.bulletText}>{detail}</T></View>)}<View style={s.costGrid}><View style={s.costCard}><T style={s.costLabel}>TUITION</T><T style={s.costValue}>{valueOf(item.costs, 0, 'Confirm with GEIC')}</T></View><View style={s.costCard}><T style={s.costLabel}>INTAKES</T><T style={s.costValue}>{item.intakes.map((entry) => entry[0]).join(', ') || 'Confirm with GEIC'}</T></View></View>{item.universities.length ? <><T style={s.sheetHeading}>Featured universities</T>{item.universities.map((name, index) => <View key={name} style={s.uni}><View style={s.uniNumber}><T style={s.uniNumberText}>{index + 1}</T></View><T style={s.uniName}>{name}</T></View>)}</> : null}</ScrollView><View style={s.sheetFooter}><Pressable onPress={() => { onClose(); onBook(item.name); }} style={s.primary}><T style={s.primaryText}>Plan my {item.name} application</T><Icon name="arrow-right" color={p.white} size={18} /></Pressable></View></View></View></Modal>;
}

function BookingSheet({ open, catalog, destination, onClose }: { open: boolean; catalog: MobileCatalog; destination?: string; onClose: () => void }) {
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState('');
  const [target, setTarget] = useState(destination ?? ''); const [level, setLevel] = useState('Postgraduate'); const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (destination) setTarget(destination); }, [destination, open]);
  if (!open) return null;
  async function submit() {
    if (!fullName.trim() || !email.trim() || !phone.trim()) { setError('Enter your name, email and phone number.'); return; }
    setError(''); setLoading(true);
    try { const response = await submitEnquiry({ fullName, email, phone, destination: target, studyLevel: level, message, referenceId: 'ai-studio-app' }); setSuccess(`Enquiry received — ${response.reference}`); }
    catch (caught) { setError(caught instanceof Error ? caught.message : 'We could not send your enquiry.'); }
    finally { setLoading(false); }
  }
  return <Modal visible transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={s.sheet}><View style={s.bookingHead}><View><T style={s.bookingTitle}>Book free counselling</T><T style={s.bookingSub}>Speak with a Trans Globe Indore specialist</T></View><Pressable onPress={onClose} style={s.close}><Icon name="close" color={p.white} size={21} /></Pressable></View>{success ? <View style={s.success}><View style={s.successIcon}><Icon name="check" color={p.white} size={35} /></View><T style={s.successTitle}>Thank you, {fullName}.</T><T style={s.successCopy}>{success}</T><Pressable onPress={onClose} style={s.primary}><T style={s.primaryText}>Done</T></Pressable></View> : <ScrollView contentContainerStyle={s.bookingContent} keyboardShouldPersistTaps="handled"><T style={s.fieldLabel}>Full name *</T><TextInput value={fullName} onChangeText={setFullName} style={s.field} placeholder="Your name" /><T style={s.fieldLabel}>Email *</T><TextInput value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" style={s.field} placeholder="you@example.com" /><T style={s.fieldLabel}>Phone / WhatsApp *</T><TextInput value={phone} onChangeText={setPhone} keyboardType="phone-pad" style={s.field} placeholder="+91" /><T style={s.fieldLabel}>Destination</T><View style={s.chipWrap}>{catalog.destinations.map((item) => <Chip key={item.id} label={item.name} selected={target === item.name} onPress={() => setTarget(item.name)} />)}</View><T style={s.fieldLabel}>Study level</T><View style={s.chipWrap}>{['Undergraduate', 'Postgraduate', 'Diploma or pathway', 'Research'].map((item) => <Chip key={item} label={item} selected={level === item} onPress={() => setLevel(item)} />)}</View><T style={s.fieldLabel}>What would you like help with?</T><TextInput value={message} onChangeText={setMessage} multiline style={[s.field, s.textarea]} placeholder="Course, intake, budget or test preparation" />{error ? <T style={s.error}>{error}</T> : null}<Pressable onPress={() => void submit()} style={s.primary}>{loading ? <ActivityIndicator color={p.white} /> : <><Icon name="calendar-check-outline" color={p.white} size={19} /><T style={s.primaryText}>Send enquiry</T></>}</Pressable><T style={s.consent}>By submitting, you agree that a GEIC counsellor may contact you about this enquiry.</T></ScrollView>}</View></View></Modal>;
}

export default function App() {
  const [fontsLoaded] = useFonts({ PlusJakartaSans_400Regular, PlusJakartaSans_600SemiBold, PlusJakartaSans_700Bold, PlusJakartaSans_800ExtraBold });
  const [catalog, setCatalog] = useState<MobileCatalog | null>(null); const [active, setActive] = useState<AppTab>('home');
  const [destination, setDestination] = useState<Destination | null>(null); const [bookingTarget, setBookingTarget] = useState<string | undefined>(); const [booking, setBooking] = useState(false);
  const [loading, setLoading] = useState(true); const [catalogError, setCatalogError] = useState('');
  const refresh = async () => { setLoading(true); setCatalogError(''); try { setCatalog(await loadCatalog()); } catch (caught) { setCatalogError(caught instanceof Error ? caught.message : 'Could not load the GEIC catalogue.'); } finally { setLoading(false); } };
  useEffect(() => { void refresh(); }, []);
  const openBooking = (nextDestination?: string) => { setBookingTarget(nextDestination); setBooking(true); };
  if (!fontsLoaded) return <View style={s.boot}><ActivityIndicator color={p.red} /></View>;
  if (!catalog) return <SafeAreaView style={s.boot}><StatusBar style="dark" /><View style={s.loading}><View style={s.brandMark}><T style={s.brandMarkText}>TG</T></View><T style={s.loadingTitle}>AI Studio App</T><T style={s.loadingCopy}>{catalogError || 'Loading the current GEIC catalogue…'}</T>{loading ? <ActivityIndicator color={p.red} /> : <Pressable onPress={() => void refresh()} style={s.retry}><T style={s.retryText}>Try again</T></Pressable>}</View></SafeAreaView>;
  const screen = active === 'home' ? <HomeTab catalog={catalog} onTab={setActive} onDestination={setDestination} onBook={() => openBooking()} /> : active === 'explore' ? <ExploreTab catalog={catalog} onDestination={setDestination} /> : active === 'advisor' ? <AdvisorTab onBook={() => openBooking()} /> : active === 'evaluate' ? <EvaluateTab catalog={catalog} onBook={openBooking} /> : <MoreTab catalog={catalog} onBook={() => openBooking()} />;
  return <SafeAreaView style={s.app}><StatusBar style="dark" /><Header onBook={() => openBooking()} onRefresh={() => void refresh()} loading={loading} />{catalogError ? <Pressable onPress={() => void refresh()} style={s.notice}><Icon name="information-outline" color={p.red} size={17} /><T style={s.noticeText}>{catalogError} Tap to retry.</T></Pressable> : null}<View style={s.content}>{screen}</View><Nav active={active} onChange={setActive} /><DestinationSheet item={destination} onClose={() => setDestination(null)} onBook={openBooking} /><BookingSheet open={booking} catalog={catalog} destination={bookingTarget} onClose={() => setBooking(false)} /></SafeAreaView>;
}

const s = StyleSheet.create({
  app: { flex: 1, backgroundColor: p.canvas }, boot: { flex: 1, backgroundColor: p.canvas, alignItems: 'center', justifyContent: 'center' }, content: { flex: 1 }, text: { color: p.navy, fontFamily: font.regular },
  header: { minHeight: 68, paddingHorizontal: 16, paddingVertical: 10, backgroundColor: p.white, borderBottomWidth: 1, borderBottomColor: p.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brandRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, brandMark: { width: 37, height: 37, borderRadius: 15, backgroundColor: p.navy, borderWidth: 2, borderColor: p.red, alignItems: 'center', justifyContent: 'center' }, brandMarkText: { color: p.white, fontFamily: font.extra, fontSize: 14 }, brandTitleRow: { flexDirection: 'row', gap: 7, alignItems: 'center' }, brandTitle: { fontFamily: font.extra, fontSize: 14 }, indore: { color: '#B91C1C', backgroundColor: '#FEE2E2', overflow: 'hidden', borderRadius: 5, paddingHorizontal: 5, paddingVertical: 2, fontFamily: font.extra, fontSize: 8 }, location: { flexDirection: 'row', alignItems: 'center', gap: 2, marginTop: 2 }, locationText: { color: p.muted, fontFamily: font.semi, fontSize: 10 }, headerButtons: { flexDirection: 'row', gap: 7 }, headerButton: { width: 38, height: 38, borderRadius: 13, borderWidth: 1, borderColor: p.line, backgroundColor: p.canvas, alignItems: 'center', justifyContent: 'center' }, headerBook: { backgroundColor: p.redSoft, borderColor: '#FECACA' },
  scroll: { padding: 16, paddingBottom: 112, gap: 18 }, hero: { height: 300, borderRadius: 26, overflow: 'hidden', backgroundColor: p.navy, justifyContent: 'flex-end' }, heroImage: { borderRadius: 26 }, overlay: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(15,23,42,0.56)' }, heroContent: { padding: 18, gap: 20 }, heroBadges: { flexDirection: 'row', gap: 7 }, heroBadge: { color: p.white, backgroundColor: '#0F172ACC', overflow: 'hidden', borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5, fontFamily: font.bold, fontSize: 9 }, heroEyebrow: { color: '#FDE68A', fontFamily: font.extra, fontSize: 10, letterSpacing: 1.4 }, heroTitle: { color: p.white, fontFamily: font.extra, fontSize: 31, lineHeight: 37, marginTop: 5 }, heroCopy: { color: '#E2E8F0', fontFamily: font.semi, fontSize: 13, lineHeight: 19, marginTop: 5, maxWidth: '90%' }, heroActions: { flexDirection: 'row', gap: 9, marginTop: 15 }, heroPrimary: { flex: 1, paddingVertical: 11, borderRadius: 13, alignItems: 'center', backgroundColor: p.red }, heroPrimaryText: { color: p.white, fontFamily: font.bold, fontSize: 11 }, heroSecondary: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 13, borderRadius: 13, borderWidth: 1, borderColor: '#FFFFFF59', backgroundColor: '#0F172A73' }, heroSecondaryText: { color: p.white, fontFamily: font.bold, fontSize: 11 },
  expoCard: { overflow: 'hidden', minHeight: 152, padding: 18, borderRadius: 24, backgroundColor: '#7F1D1D' }, expoGlow: { position: 'absolute', right: -45, top: -35, width: 150, height: 150, borderRadius: 75, backgroundColor: '#F59E0B33' }, expoKicker: { color: '#FDE68A', fontFamily: font.extra, fontSize: 9, letterSpacing: 1.2 }, expoTitle: { color: p.white, maxWidth: '85%', marginTop: 6, fontFamily: font.extra, fontSize: 19, lineHeight: 25 }, expoCopy: { color: '#FECACA', marginTop: 8, fontFamily: font.semi, fontSize: 11 }, expoFooter: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 15 }, expoAction: { color: '#FDE68A', fontFamily: font.bold, fontSize: 11 },
  titleRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10 }, eyebrow: { color: p.red, marginBottom: 5, fontFamily: font.extra, fontSize: 9, letterSpacing: 1.25 }, heading: { fontFamily: font.extra, fontSize: 19, lineHeight: 25 }, titleAction: { flexDirection: 'row', alignItems: 'center' }, titleActionText: { color: p.red, fontFamily: font.bold, fontSize: 11 },
  quickGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, quickCard: { width: '48.5%', minHeight: 118, padding: 13, borderRadius: 19, backgroundColor: p.white, borderWidth: 1, borderColor: p.line, justifyContent: 'space-between' }, quickIcon: { width: 40, height: 40, borderRadius: 14, backgroundColor: p.redSoft, alignItems: 'center', justifyContent: 'center' }, quickTitle: { maxWidth: '85%', fontFamily: font.bold, fontSize: 13 }, statPanel: { flexDirection: 'row', paddingVertical: 13, borderRadius: 18, backgroundColor: '#F1F5F9' }, statCell: { flex: 1, alignItems: 'center', borderRightWidth: 1, borderRightColor: p.line }, statValue: { fontFamily: font.extra, fontSize: 15 }, statLabel: { color: p.muted, marginTop: 3, fontFamily: font.semi, fontSize: 8, textAlign: 'center' }, rail: { gap: 12, paddingRight: 16 }, destinationCard: { width: 210, overflow: 'hidden', borderRadius: 19, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, destinationImage: { width: '100%', height: 105 }, destinationBody: { padding: 12 }, destinationName: { fontFamily: font.extra, fontSize: 15 }, destinationTagline: { minHeight: 30, color: p.muted, marginTop: 4, fontSize: 10, lineHeight: 15 }, destinationMeta: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8, paddingTop: 9, borderTopWidth: 1, borderTopColor: '#F1F5F9' }, destinationMetaText: { flex: 1, color: p.red, fontFamily: font.bold, fontSize: 9 }, roadmap: { gap: 8 }, roadmapRow: { flexDirection: 'row', gap: 12, padding: 13, borderRadius: 17, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, step: { width: 39, height: 39, borderRadius: 13, backgroundColor: p.redSoft, alignItems: 'center', justifyContent: 'center' }, stepText: { color: p.red, fontFamily: font.extra, fontSize: 11 }, roadmapTitle: { fontFamily: font.bold, fontSize: 13 }, roadmapCopy: { color: p.muted, marginTop: 3, fontSize: 10, lineHeight: 15 },
  search: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 13, borderRadius: 15, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, searchInput: { flex: 1, minHeight: 48, color: p.navy, fontFamily: font.regular, fontSize: 13 }, segmented: { flexDirection: 'row', gap: 4, padding: 4, borderRadius: 14, backgroundColor: '#E2E8F0' }, segment: { flex: 1, minHeight: 36, paddingHorizontal: 5, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, segmentOn: { backgroundColor: p.white }, segmentText: { color: p.muted, fontFamily: font.bold, fontSize: 10 }, segmentTextOn: { color: p.navy }, list: { gap: 10 }, listCard: { minHeight: 94, flexDirection: 'row', gap: 12, alignItems: 'center', padding: 9, borderRadius: 17, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, listImage: { width: 72, height: 72, borderRadius: 12 }, listTitle: { fontFamily: font.bold, fontSize: 13 }, listCopy: { color: p.muted, marginTop: 3, fontSize: 10, lineHeight: 15 }, listTag: { color: p.red, marginTop: 7, fontFamily: font.bold, fontSize: 9 }, serviceCard: { minHeight: 92, flexDirection: 'row', gap: 12, padding: 13, borderRadius: 17, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, serviceIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: p.redSoft, alignItems: 'center', justifyContent: 'center' }, serviceIndex: { color: p.red, fontFamily: font.extra, fontSize: 9, letterSpacing: 1 },
  advisorPage: { flex: 1, paddingBottom: 84 }, advisorHeader: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 16, paddingVertical: 12, backgroundColor: p.white, borderBottomWidth: 1, borderBottomColor: p.line }, advisorBot: { width: 39, height: 39, borderRadius: 14, backgroundColor: p.red, alignItems: 'center', justifyContent: 'center' }, advisorTitle: { fontFamily: font.extra, fontSize: 13 }, advisorSub: { color: p.muted, marginTop: 2, fontSize: 9 }, advisorBook: { paddingHorizontal: 10, paddingVertical: 7, borderRadius: 10, backgroundColor: p.redSoft, borderWidth: 1, borderColor: '#FECACA' }, advisorBookText: { color: p.red, fontFamily: font.bold, fontSize: 10 }, chatList: { padding: 16, gap: 12 }, messageRow: { flexDirection: 'row', gap: 7, alignItems: 'flex-start' }, messageRowUser: { flexDirection: 'row-reverse' }, avatar: { width: 28, height: 28, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, botAvatar: { backgroundColor: p.red }, userAvatar: { backgroundColor: p.navy }, bubble: { maxWidth: '82%', padding: 11, borderRadius: 16 }, botBubble: { backgroundColor: p.white, borderWidth: 1, borderColor: p.line, borderTopLeftRadius: 4 }, userBubble: { backgroundColor: p.navy, borderTopRightRadius: 4 }, messageText: { fontSize: 12, lineHeight: 19 }, userText: { color: p.white }, loadingReply: { flexDirection: 'row', alignItems: 'center', gap: 8, marginHorizontal: 16, padding: 10, borderRadius: 13, backgroundColor: p.white }, loadingReplyText: { color: p.muted, fontSize: 10 }, prompts: { gap: 7, paddingHorizontal: 14, paddingVertical: 8, borderTopWidth: 1, borderTopColor: p.line }, prompt: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 10, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, promptText: { color: p.slate, fontFamily: font.semi, fontSize: 10 }, composer: { position: 'absolute', left: 0, right: 0, bottom: 0, flexDirection: 'row', gap: 8, padding: 10, backgroundColor: p.white, borderTopWidth: 1, borderTopColor: p.line }, composerInput: { flex: 1, minHeight: 46, paddingHorizontal: 12, borderRadius: 14, backgroundColor: p.canvas, color: p.navy, fontFamily: font.regular, fontSize: 12 }, send: { width: 46, height: 46, borderRadius: 14, backgroundColor: p.red, alignItems: 'center', justifyContent: 'center' }, sendOff: { opacity: 0.45 },
  formCard: { padding: 15, borderRadius: 20, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, fieldLabel: { marginTop: 8, marginBottom: 6, fontFamily: font.bold, fontSize: 11 }, field: { minHeight: 45, paddingHorizontal: 11, borderRadius: 12, backgroundColor: p.canvas, borderWidth: 1, borderColor: p.line, color: p.navy, fontFamily: font.regular, fontSize: 12 }, textarea: { minHeight: 86, paddingTop: 11, textAlignVertical: 'top' }, chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 9, backgroundColor: '#F1F5F9', borderWidth: 1, borderColor: '#E2E8F0' }, chipOn: { backgroundColor: p.red, borderColor: p.red }, chipText: { color: p.slate, fontFamily: font.semi, fontSize: 10 }, chipTextOn: { color: p.white }, error: { color: '#B91C1C', marginTop: 9, fontFamily: font.semi, fontSize: 10, lineHeight: 15 }, primary: { minHeight: 48, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center', marginTop: 16, paddingHorizontal: 14, borderRadius: 14, backgroundColor: p.red }, primaryText: { color: p.white, fontFamily: font.bold, fontSize: 12 }, result: { padding: 17, borderRadius: 22, backgroundColor: p.navy }, score: { width: 94, height: 94, borderRadius: 47, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', backgroundColor: '#1E293B', borderWidth: 5, borderColor: p.amber }, scoreValue: { color: p.white, fontFamily: font.extra, fontSize: 29 }, scoreLabel: { color: '#FDE68A', fontFamily: font.bold, fontSize: 8 }, resultTitle: { color: p.white, marginTop: 12, fontFamily: font.extra, fontSize: 18, textAlign: 'center' }, resultCopy: { color: '#CBD5E1', marginTop: 7, fontSize: 11, lineHeight: 17, textAlign: 'center' }, resultHeading: { color: '#FDE68A', marginTop: 17, marginBottom: 7, fontFamily: font.extra, fontSize: 9, letterSpacing: 1.1 }, match: { flexDirection: 'row', gap: 9, alignItems: 'center', padding: 10, marginBottom: 7, borderRadius: 13, backgroundColor: '#1E293B' }, matchIcon: { width: 30, height: 30, borderRadius: 10, backgroundColor: p.redSoft, alignItems: 'center', justifyContent: 'center' }, matchName: { color: p.white, fontFamily: font.bold, fontSize: 11 }, matchCopy: { color: '#CBD5E1', marginTop: 2, fontSize: 9 }, bullet: { flexDirection: 'row', gap: 7, alignItems: 'flex-start', marginVertical: 4 }, bulletText: { flex: 1, color: p.slate, fontSize: 11, lineHeight: 17 }, disclaimer: { color: '#94A3B8', marginTop: 14, fontSize: 9, lineHeight: 14 },
  moreCard: { flexDirection: 'row', gap: 11, padding: 10, borderRadius: 18, backgroundColor: p.white, borderWidth: 1, borderColor: p.line }, moreImage: { width: 78, height: 92, borderRadius: 12 }, moreAction: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 8 }, moreActionText: { color: p.red, fontFamily: font.bold, fontSize: 10 }, contactCard: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 14, borderRadius: 17, backgroundColor: '#EFF6FF' }, contactTitle: { fontFamily: font.bold, fontSize: 12 }, contactCopy: { color: p.muted, marginTop: 3, fontSize: 10 }, contactButton: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 10, backgroundColor: p.white, borderWidth: 1, borderColor: '#BFDBFE' }, contactButtonText: { color: p.red, fontFamily: font.bold, fontSize: 10 },
  navWrap: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingHorizontal: 12, paddingBottom: 10 }, nav: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 3, borderRadius: 23, backgroundColor: '#0F172AF2', borderWidth: 1, borderColor: '#334155' }, navItem: { minWidth: 56, alignItems: 'center', paddingTop: 7 }, navAdvisor: { marginTop: -23 }, navIcon: { width: 30, height: 25, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, navIconOn: { backgroundColor: p.red }, navIconAdvisor: { width: 46, height: 46, borderRadius: 16, backgroundColor: p.red, borderWidth: 3, borderColor: p.navy }, navLabel: { color: '#94A3B8', marginTop: 2, fontFamily: font.semi, fontSize: 8 }, navLabelOn: { color: p.white, fontFamily: font.bold },
  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: '#0F172AAD' }, sheet: { maxHeight: '92%', overflow: 'hidden', borderTopLeftRadius: 27, borderTopRightRadius: 27, backgroundColor: p.white }, sheetHero: { minHeight: 185, justifyContent: 'flex-end' }, sheetTop: { position: 'absolute', top: 14, left: 14, right: 14, flexDirection: 'row', justifyContent: 'space-between' }, sheetBadge: { overflow: 'hidden', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 9, backgroundColor: '#0F172ACC', color: p.white, fontFamily: font.bold, fontSize: 9 }, close: { width: 33, height: 33, borderRadius: 16, backgroundColor: '#0F172ACC', alignItems: 'center', justifyContent: 'center' }, sheetHeroCopy: { padding: 16 }, sheetTitle: { color: p.white, fontFamily: font.extra, fontSize: 26 }, sheetTagline: { color: '#E2E8F0', marginTop: 3, fontSize: 11 }, sheetContent: { padding: 17, gap: 10 }, sheetHeading: { marginTop: 3, fontFamily: font.extra, fontSize: 14 }, sheetCopy: { color: p.muted, fontSize: 11, lineHeight: 17 }, costGrid: { flexDirection: 'row', gap: 9, marginTop: 5 }, costCard: { flex: 1, padding: 11, borderRadius: 13, backgroundColor: '#FFFBEB', borderWidth: 1, borderColor: '#FDE68A' }, costLabel: { color: '#92400E', fontFamily: font.extra, fontSize: 8, letterSpacing: 1 }, costValue: { color: p.navy, marginTop: 5, fontFamily: font.bold, fontSize: 10, lineHeight: 14 }, uni: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 10, borderRadius: 12, backgroundColor: p.canvas }, uniNumber: { width: 25, height: 25, borderRadius: 8, backgroundColor: p.redSoft, alignItems: 'center', justifyContent: 'center' }, uniNumberText: { color: p.red, fontFamily: font.bold, fontSize: 10 }, uniName: { flex: 1, fontFamily: font.semi, fontSize: 11 }, sheetFooter: { padding: 14, borderTopWidth: 1, borderTopColor: p.line },
  bookingHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 17, backgroundColor: p.navy }, bookingTitle: { color: p.white, fontFamily: font.extra, fontSize: 17 }, bookingSub: { color: '#CBD5E1', marginTop: 3, fontSize: 10 }, bookingContent: { padding: 17, paddingBottom: 32 }, consent: { color: p.muted, marginTop: 10, fontSize: 9, lineHeight: 14, textAlign: 'center' }, success: { alignItems: 'center', gap: 12, padding: 30 }, successIcon: { width: 62, height: 62, borderRadius: 31, backgroundColor: p.emerald, alignItems: 'center', justifyContent: 'center' }, successTitle: { fontFamily: font.extra, fontSize: 18 }, successCopy: { color: p.muted, fontSize: 11, lineHeight: 17, textAlign: 'center' },
  notice: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: p.redSoft, borderBottomWidth: 1, borderBottomColor: '#FECACA' }, noticeText: { flex: 1, color: '#991B1B', fontFamily: font.semi, fontSize: 10 }, loading: { width: '80%', maxWidth: 320, alignItems: 'center', gap: 12 }, loadingTitle: { fontFamily: font.extra, fontSize: 20 }, loadingCopy: { color: p.muted, fontSize: 12, lineHeight: 18, textAlign: 'center' }, retry: { paddingHorizontal: 15, paddingVertical: 10, borderRadius: 12, backgroundColor: p.red }, retryText: { color: p.white, fontFamily: font.bold, fontSize: 12 },
});
