@extends('admin.layout')

@section('title', 'Settings | Trans Globe Indore LMS')
@section('crumb', 'Settings')
@section('backUrl', route('admin.dashboard'))
@section('backLabel', 'Back to dashboard')

@section('content')
    <section class="page-head"><div><span class="eyebrow">Dashboard preferences</span><h1>Settings</h1></div><p>Choose how your personal dashboard behaves without changing the public website.</p></section>
    @if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
    <section class="account-layout"><form class="panel account-card account-form" method="post" action="{{ route('admin.settings.update') }}">@csrf @method('PUT')<div class="account-card__head"><div><h2>Workspace preferences</h2><p>These settings apply only to {{ $adminUser->name }}.</p></div></div><div class="account-form__grid"><div class="field account-form__full"><label for="default-screen">Default screen after sign in</label><select class="select" id="default-screen" name="default_screen"><option value="dashboard" @selected(($preferences['default_screen'] ?? 'dashboard') === 'dashboard')>Dashboard overview</option>@can('content.manage')<option value="pages" @selected(($preferences['default_screen'] ?? '') === 'pages')>Website content</option>@endcan @can('media.manage')<option value="media" @selected(($preferences['default_screen'] ?? '') === 'media')>Media library</option>@endcan</select></div><label class="access-switch account-form__full"><span><strong>Start with sidebar collapsed</strong><span>Use the compact icon rail when the dashboard opens on desktop.</span></span><input type="checkbox" name="sidebar_collapsed" value="1" @checked($preferences['sidebar_collapsed'] ?? false)></label><label class="access-switch account-form__full"><span><strong>Email notifications</strong><span>Receive important dashboard and enquiry notifications when notification delivery is configured.</span></span><input type="checkbox" name="email_notifications" value="1" @checked($preferences['email_notifications'] ?? true)></label></div><div class="account-actions"><button class="button" type="submit">Save settings</button></div></form><aside class="panel account-summary"><span class="account-summary__avatar" aria-hidden="true"><svg viewBox="0 0 24 24" style="width:27px;height:27px;fill:none;stroke:currentColor;stroke-width:1.8"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z"/></svg></span><div><h2>Personal preferences</h2><p>These choices never alter website content, branding, or another administrator’s workspace.</p></div><a class="button button--quiet" href="{{ route('admin.profile.edit') }}">Open my profile</a></aside></section>
@endsection
