@extends('admin.layout')

@section('content')
<style>
    .blog-editor{display:grid;grid-template-columns:minmax(0,1fr) 280px;align-items:start;gap:20px}.blog-editor__main,.blog-editor__side{display:grid;gap:18px}.blog-editor__card{display:grid;gap:18px;padding:22px}.blog-editor__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.blog-editor__card label{display:grid;gap:7px;color:var(--admin-ink);font-size:12px;font-weight:700}.blog-editor__card input,.blog-editor__card textarea,.blog-editor__card select{width:100%;min-height:44px;padding:0 13px;border:1px solid var(--admin-line);border-radius:var(--admin-radius-control);background:#fff;color:var(--admin-ink);font-size:12px;outline:none}.blog-editor__card textarea{min-height:120px;padding:12px 13px;resize:vertical}.blog-editor__card input:focus,.blog-editor__card textarea:focus,.blog-editor__card select:focus{border-color:var(--admin-primary);box-shadow:0 0 0 3px rgba(227,30,36,.11)}.blog-editor__section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.blog-editor__section-head h2{margin:0;color:var(--admin-ink);font-size:15px}.blog-editor__section-head p{margin:4px 0 0;color:var(--admin-muted);font-size:11px}.blog-section-row{display:grid;grid-template-columns:minmax(170px,.7fr) minmax(0,1.3fr) auto;align-items:start;gap:9px;padding:12px;border:1px solid var(--admin-line);border-radius:14px;background:#fafcff}.blog-section-row input,.blog-section-row textarea{min-height:40px}.blog-section-row textarea{min-height:75px}.blog-tags{display:flex;flex-wrap:wrap;gap:8px}.blog-tag-row{display:flex;align-items:center;gap:8px;width:100%}.blog-tag-row input{flex:1}.blog-editor__side-card{display:grid;gap:14px;padding:20px}.blog-editor__side-card h2{margin:0;color:var(--admin-ink);font-size:15px}.blog-editor__side-card p{margin:0;color:var(--admin-muted);font-size:12px;line-height:1.55}.blog-editor__side-card img{display:block;width:100%;aspect-ratio:2/1;object-fit:cover;border-radius:13px;background:#eef3f8}.blog-editor__actions{display:flex;justify-content:flex-end;gap:10px}@media(max-width:900px){.blog-editor{grid-template-columns:1fr}}@media(max-width:680px){.blog-editor__grid{grid-template-columns:1fr}.blog-section-row{grid-template-columns:1fr}.blog-editor__actions{align-items:stretch;flex-direction:column-reverse}.blog-editor__actions .admin-button{width:100%}}
</style>

<div class="admin-page-head"><div><span class="admin-kicker">Website content</span><h1>{{ $mode === 'create' ? 'Create blog post' : 'Edit blog post' }}</h1><p>Write the article once and publish it to the public blog list and detail page.</p></div><a class="admin-button" href="{{ route('admin.blogs.index') }}">Back to blog posts</a></div>
@if($errors->any())<div class="error-summary"><strong>Please check the highlighted details</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

<form class="blog-editor" method="post" action="{{ $mode === 'create' ? route('admin.blogs.store') : route('admin.blogs.update', $post) }}">
    @csrf @if($mode === 'edit') @method('PUT') @endif
    <div class="blog-editor__main">
        <section class="admin-card blog-editor__card"><div class="blog-editor__grid"><label>Title<input name="title" value="{{ old('title', $post->title) }}" required></label><label>Category<input name="category" value="{{ old('category', $post->category) }}" required></label><label>URL slug<input name="slug" value="{{ old('slug', $post->slug) }}" placeholder="auto-generated from title"></label><label>Read time<input name="read_time" value="{{ old('read_time', $post->read_time) }}" placeholder="5 min read" required></label><label>Author<input name="author" value="{{ old('author', $post->author) }}" required></label><label>Publish date<input type="date" name="published_at" value="{{ old('published_at', optional($post->published_at)->format('Y-m-d')) }}"></label></div><label>Excerpt<textarea name="excerpt" rows="3" required>{{ old('excerpt', $post->excerpt) }}</textarea></label><label>Hero image URL or media path<input name="image" value="{{ old('image', $post->image) }}" placeholder="assets/transglobe/...jpg"><small>Use a Media library path or an absolute image URL.</small></label><label>Introduction<textarea name="intro" rows="5" required>{{ old('intro', $post->intro) }}</textarea></label></section>
        <section class="admin-card blog-editor__card"><div class="blog-editor__section-head"><div><h2>Article sections</h2><p>Add, remove and edit the headings and body copy shown on the detail page.</p></div><button class="admin-button" type="button" id="add-blog-section">+ Add section</button></div><div id="blog-sections">@foreach(old('sections', $post->sections ?: [['title' => '', 'copy' => '']]) as $i => $section)<div class="blog-section-row"><input name="sections[{{ $i }}][title]" value="{{ $section['title'] ?? '' }}" placeholder="Section heading"><textarea name="sections[{{ $i }}][copy]" placeholder="Section copy">{{ $section['copy'] ?? '' }}</textarea><button class="admin-button admin-button--danger remove-blog-section" type="button">Remove</button></div>@endforeach</div></section>
    </div>
    <aside class="blog-editor__side"><section class="admin-card blog-editor__side-card"><h2>Publishing</h2><p>New and edited posts save as drafts. Publish only after checking the public preview.</p><label class="blog-featured"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured', $post->is_featured))> Feature this post on the homepage</label>@if($post->exists && $post->image)<img src="{{ asset($post->image) }}" alt="Current hero image preview">@endif</section><section class="admin-card blog-editor__card"><div class="blog-editor__section-head"><div><h2>Topics</h2><p>Use tags to help readers scan related guidance.</p></div><button class="admin-button" type="button" id="add-blog-tag">+ Add tag</button></div><div id="blog-tags" class="blog-tags">@foreach(old('tags', $post->tags ?: ['']) as $i => $tag)<div class="blog-tag-row"><input name="tags[{{ $i }}]" value="{{ $tag }}" placeholder="e.g. Visa guidance"><button class="admin-button admin-button--danger remove-blog-tag" type="button" aria-label="Remove tag">×</button></div>@endforeach</div></section><div class="blog-editor__actions"><a class="admin-button" href="{{ route('admin.blogs.index') }}">Cancel</a><button class="admin-button admin-button--primary" type="submit">{{ $mode === 'create' ? 'Create draft' : 'Save changes' }} <span aria-hidden="true">→</span></button></div></aside>
</form>
<script>
document.addEventListener('DOMContentLoaded',()=>{const sections=document.getElementById('blog-sections');const tags=document.getElementById('blog-tags');let sectionIndex=sections.children.length;let tagIndex=tags.children.length;document.getElementById('add-blog-section').addEventListener('click',()=>{const row=document.createElement('div');row.className='blog-section-row';row.innerHTML=`<input name="sections[${sectionIndex}][title]" placeholder="Section heading"><textarea name="sections[${sectionIndex}][copy]" placeholder="Section copy"></textarea><button class="admin-button admin-button--danger remove-blog-section" type="button">Remove</button>`;sections.appendChild(row);sectionIndex++});document.getElementById('add-blog-tag').addEventListener('click',()=>{const row=document.createElement('div');row.className='blog-tag-row';row.innerHTML=`<input name="tags[${tagIndex}]" placeholder="e.g. Visa guidance"><button class="admin-button admin-button--danger remove-blog-tag" type="button" aria-label="Remove tag">×</button>`;tags.appendChild(row);tagIndex++});sections.addEventListener('click',e=>{if(e.target.closest('.remove-blog-section'))e.target.closest('.blog-section-row').remove()});tags.addEventListener('click',e=>{if(e.target.closest('.remove-blog-tag')&&tags.children.length>1)e.target.closest('.blog-tag-row').remove()})});
</script>
@endsection
