@extends('admin.layout')

@section('title', 'My profile | Trans Globe Indore LMS')
@section('crumb', 'My profile')
@section('backUrl', route('admin.dashboard'))
@section('backLabel', 'Back to dashboard')

@section('content')
    <section class="page-head"><div><span class="eyebrow">Personal account</span><h1>My profile</h1></div><p>Keep your identity and sign-in information accurate and secure.</p></section>
    @if(session('status'))<div class="notice" role="status">{{ session('status') }}</div>@endif
    <section class="account-layout"><div class="account-stack"><form class="panel account-card account-form" method="post" action="{{ route('admin.profile.update') }}">@csrf @method('PUT')<div class="account-card__head"><div><h2>Profile details</h2><p>This information identifies you throughout the dashboard.</p></div></div><div class="account-form__grid"><div class="field"><label for="profile-name">Full name</label><input class="input" id="profile-name" name="name" value="{{ old('name', $adminUser->name) }}" autocomplete="name" required>@error('name')<small role="alert" style="color:#9f2029">{{ $message }}</small>@enderror</div><div class="field"><label for="profile-email">Email address</label><input class="input" id="profile-email" type="email" name="email" value="{{ old('email', $adminUser->email) }}" autocomplete="email" required>@error('email')<small role="alert" style="color:#9f2029">{{ $message }}</small>@enderror</div></div><div class="account-actions"><button class="button" type="submit">Save profile</button></div></form><form class="panel account-card account-form" method="post" action="{{ route('admin.profile.password') }}">@csrf @method('PUT')<div class="account-card__head"><div><h2>Change password</h2><p>Confirm your current password before creating a new one.</p></div></div><div class="account-form__grid"><div class="field account-form__full"><label for="current-password">Current password</label><input class="input" id="current-password" type="password" name="current_password" autocomplete="current-password" required>@error('current_password')<small role="alert" style="color:#9f2029">{{ $message }}</small>@enderror</div><div class="field"><label for="new-password">New password</label><input class="input" id="new-password" type="password" name="password" autocomplete="new-password" required>@error('password')<small role="alert" style="color:#9f2029">{{ $message }}</small>@enderror</div><div class="field"><label for="new-password-confirmation">Confirm new password</label><input class="input" id="new-password-confirmation" type="password" name="password_confirmation" autocomplete="new-password" required></div></div><div class="account-actions"><button class="button" type="submit">Change password</button></div></form></div><aside class="panel account-summary"><span class="account-summary__avatar">{{ strtoupper(substr($adminUser->name, 0, 1)) }}</span><div><h2>{{ $adminUser->name }}</h2><p>{{ $adminUser->email }}</p></div><div class="account-facts"><div class="account-fact"><span>Role</span><strong>{{ $adminUser->adminRoleLabel() }}</strong></div><div class="account-fact"><span>Status</span><strong>Active</strong></div><div class="account-fact"><span>Member since</span><strong>{{ $adminUser->created_at->format('M Y') }}</strong></div></div><a class="button button--quiet" href="{{ route('admin.settings.edit') }}">Dashboard settings</a></aside></section>
@endsection
