import React,{useState} from 'react';
import {Alert,Platform,FlatList,ImageBackground,RefreshControl,ScrollView,Share,View,useWindowDimensions} from 'react-native';
import {useNavigation,type RouteProp} from '@react-navigation/native';
import {assetUrl,canRegister,collections,filterRecords,label,recordKey,text,title,type Collection,type RecordData} from './native-core';
import {origin} from './native-api';
import {Button,Card,Check,Chips,Empty,ErrorNote,Field,Fields,Heading,Icon,IconButton,ItemCard,Photo,Screen,T,colors,openExternal,s,useApp,type Nav,type Routes} from './native-ui';
function openItem(nav:Nav,group:Collection,item:RecordData){nav.navigate('Detail',{collection:group,id:String(item.id)});}
function Rail({group}:{group:Collection}){
 const app=useApp(),nav=useNavigation<Nav>();const info=collections.find(g=>g.key===group)!;
 return <View style={{gap:12}}><Heading title={info.title}/>{app.data[group].length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{app.data[group].map(item=><ItemCard key={String(item.id)} item={item} compact onPress={()=>openItem(nav,group,item)} saved={app.saved.includes(recordKey(group,item))} onSave={()=>app.toggleSave(recordKey(group,item))}/>)}</ScrollView>:<Empty/>}<Button label={'View all '+info.title.toLowerCase()} secondary onPress={()=>nav.navigate('Directory',{collection:group})}/></View>;
}
export function HomeScreen(){
 const app=useApp(),nav=useNavigation<Nav>(),{width}=useWindowDimensions();const heroWidth=Math.min(width-32,650);
 return <ScrollView style={s.screen} contentContainerStyle={s.scroll} refreshControl={<RefreshControl refreshing={app.refreshing} onRefresh={()=>void app.refresh()}/>}><View style={s.row}><IconButton name="menu" label="Open navigation menu" onPress={()=>nav.navigate('Menu')}/><View style={{flex:1}}/><IconButton name="bell-outline" label="Notifications" onPress={()=>nav.navigate('Directory',{collection:'NOTIFICATIONS'})}/><IconButton name="phone-outline" label="Call GEIC" onPress={()=>void openExternal('tel:'+text(app.data.GEIC_BRAND.phone))}/></View><ErrorNote message={app.error||app.storageError}/>
 <ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{app.data.HERO_SLIDES.map(slide=><ImageBackground key={String(slide.id)} source={{uri:assetUrl(slide.imageUrl,origin)}} imageStyle={{borderRadius:18}} style={[s.hero,{width:heroWidth}]}><View style={{position:'absolute',inset:0,backgroundColor:'rgba(15,23,42,.58)'}}/><T style={{color:'#fde68a',fontFamily:'JakartaBold'}}>{text(slide.badge)}</T><T style={s.heroTitle}>{text(slide.title)} {text(slide.titleHighlight)}</T><T style={{color:'#fff'}}>{text(slide.description)}</T><View style={s.row}><Button label={text(slide.primaryCta)} onPress={()=>nav.navigate('Booking',{destination:text(slide.titleHighlight)})} style={{flex:1}}/><Button label="Explore" secondary onPress={()=>nav.navigate('Detail',{collection:'STUDY_DESTINATIONS',id:String(slide.id)})}/></View></ImageBackground>)}</ScrollView>
 <Button label="Search services, tests, events, universities…" secondary icon="magnify" onPress={()=>nav.navigate('Search')}/>
 <Card style={{backgroundColor:'#1c1917',borderColor:'#292524'}}><T style={{color:'#fb7185',fontFamily:'JakartaBold'}}>DECISION TOOL · Side-by-Side Table</T><T style={[s.title,{color:'#fff'}]}>Compare Universities for Your Intake</T><T style={{color:'#cbd5e1'}}>Analyze tuition fees, acceptance rates, and IELTS/GRE requirements side-by-side.</T><Button label="Launch University Comparison" icon="compare-horizontal" onPress={()=>nav.navigate('Compare')}/></Card>
 <Card style={{backgroundColor:'#7f1d1d'}}><T style={{color:'#fde68a',fontFamily:'JakartaBold'}}>MAJOR INDORE EVENT</T><T style={[s.title,{color:'#fff'}]}>{text(app.data.UPCOMING_EXPO.title)}</T><T style={{color:'#fff'}}>{text(app.data.UPCOMING_EXPO.subtitle)}</T><T style={{color:'#fecaca'}}>{text(app.data.UPCOMING_EXPO.date)}</T><Button label="View events" secondary onPress={()=>nav.navigate('Directory',{collection:'UPCOMING_EVENTS_LIST'})}/></Card>
 <Heading title="Build your global study plan" eyebrow="Start here"/><View style={s.grid}>{[['Explore Countries','earth',()=>nav.navigate('Main',{screen:'Explore'})],['AI Advisor','message-text-outline',()=>nav.navigate('Main',{screen:'Advisor'})],['Profile Evaluator','shield-check-outline',()=>nav.navigate('Main',{screen:'Evaluate'})],['Free Counselling','calendar-check-outline',()=>nav.navigate('Booking')]].map(([caption,icon,action])=><Card key={String(caption)} style={s.half}><Icon name={String(icon)} color={colors.red}/><Button label={String(caption)} secondary onPress={action as ()=>void}/></Card>)}</View>
 <Card><View style={s.grid}>{app.data.GEIC_STATS.map((stat,i)=><View key={i} style={s.half}><T style={s.heading}>{text(stat.value)}</T><T style={s.muted}>{text(stat.label)}</T></View>)}</View></Card>
 <Rail group="STUDY_DESTINATIONS"/><Rail group="GLOBAL_UNIVERSITIES"/><Rail group="GEIC_SERVICES"/><Rail group="ENGLISH_TESTS"/><Rail group="UPCOMING_EVENTS_LIST"/><Rail group="GEIC_BLOGS"/><Rail group="STUDENT_REVIEWS"/>
 <Heading title="Four simple milestones"/>{app.data.FOUR_STEPS.map((step,i)=><Card key={i}><T style={s.eyebrow}>{text(step.step)}</T><T style={s.title}>{text(step.title)}</T><T>{text(step.desc)}</T></Card>)}
 <Heading title="Frequently Asked Questions"/>{app.data.FAQS.map((faq,i)=><Accordion key={i} question={text(faq.question)} answer={text(faq.answer)}/>)}
 <Button label="Visit or contact our Indore office" secondary onPress={()=>nav.navigate('Contact')}/></ScrollView>;
}
function Accordion({question,answer}:{question:string;answer:string}){const [open,setOpen]=useState(false);return <Card><Button label={question} secondary onPress={()=>setOpen(!open)}/>{open&&<T>{answer}</T>}</Card>;}
export function DirectoryScreen({route}:{route:RouteProp<Routes,'Directory'>}) {return <Directory group={route.params.collection}/>;}
function Directory({group}:{group:Collection}){
 const app=useApp(),nav=useNavigation<Nav>();const [query,setQuery]=useState(''),[country,setCountry]=useState('All');const entries=filterRecords(app.data[group],query,country);
 const countries=['All',...app.data.STUDY_DESTINATIONS.map(d=>text(d.name))];
 return <View style={s.screen}><View style={{padding:16,gap:12}}><Heading title={collections.find(g=>g.key===group)!.title} copy={entries.length+' results'}/><Field label="Search" value={query} onChangeText={setQuery}/>{['STUDY_DESTINATIONS','GLOBAL_UNIVERSITIES'].includes(group)&&<Chips items={countries} selected={country} onSelect={setCountry}/>}</View><FlatList data={entries} keyExtractor={item=>String(item.id)} contentContainerStyle={{padding:16,gap:14,paddingBottom:32}} keyboardShouldPersistTaps="handled" ListEmptyComponent={<Empty message="No matching results. Try another search or filter."/>} refreshControl={<RefreshControl refreshing={app.refreshing} onRefresh={()=>void app.refresh()}/>} renderItem={({item})=><ItemCard item={item} saved={app.saved.includes(recordKey(group,item))} onSave={()=>app.toggleSave(recordKey(group,item))} onPress={()=>openItem(nav,group,item)}/>}/></View>;
}
export function ExploreScreen(){const [group,setGroup]=useState<Collection>('STUDY_DESTINATIONS');return <View style={s.screen}><View style={{paddingHorizontal:16}}><Chips items={['Study Destinations','Universities']} selected={group==='STUDY_DESTINATIONS'?'Study Destinations':'Universities'} onSelect={v=>setGroup(v==='Universities'?'GLOBAL_UNIVERSITIES':'STUDY_DESTINATIONS')}/></View><Directory key={group} group={group}/></View>;}
export function MoreScreen(){const [section,setSection]=useState('Services');const nav=useNavigation<Nav>();const map:Record<string,Collection>={Services:'GEIC_SERVICES',Events:'UPCOMING_EVENTS_LIST',Tests:'ENGLISH_TESTS',Blogs:'GEIC_BLOGS'};
 return <View style={s.screen}><View style={{padding:16,gap:12}}><Heading title="Explore Trans Globe" eyebrow="Student Portal & Resources"/><Chips items={['Services','Events','Tests','Blogs','My Saved','About','Contact Us']} selected={section} onSelect={v=>{if(v==='My Saved')nav.navigate('Saved');else if(v==='About')nav.navigate('About');else if(v==='Contact Us')nav.navigate('Contact');else setSection(v);}}/></View><Directory key={section} group={map[section]}/></View>;
}
const imageKeys=['imageUrl','flagUrl','bannerImage','bannerUrl','coverImage','campusImage','logoUrl','heroImage'];
export function DetailScreen({route}:{route:RouteProp<Routes,'Detail'>}) {
 const app=useApp(),nav=useNavigation<Nav>();const {collection:group,id}=route.params;const item=app.data[group].find(x=>String(x.id)===id);
 if(!item)return <Screen><Empty message="This item is no longer in the current catalogue."/></Screen>;
 const isEvent=group==='UPCOMING_EVENTS_LIST';const kind=isEvent?'event':group==='GEIC_SERVICES'?'service':'counselling';
 return <Screen><Photo value={item.imageUrl||item.bannerImage||item.bannerUrl||item.coverImage||item.campusImage}/><Heading title={title(item)}/><View style={s.row}><Button label={app.saved.includes(recordKey(group,item))?'Remove from Saved':'Save to My Collection'} secondary onPress={()=>app.toggleSave(recordKey(group,item))} style={{flex:1}}/><IconButton name="share-variant" label="Share details" onPress={()=>void Share.share({message:title(item)+'\n'+text(item.description||item.fullDesc||item.overview||item.excerpt)+'\nhttps://www.geic.in'}).catch(()=>Alert.alert('Sharing unavailable'))}/></View>
 <Card><Fields value={item} omit={['id','title','name','slug','iconName',...imageKeys]}/></Card>
 {group==='STUDY_DESTINATIONS'&&<Button label="Visa process & document checklist" secondary onPress={()=>nav.navigate('Visa',{country:text(item.name)})}/>}
 {group==='GLOBAL_UNIVERSITIES'&&<Button label="Compare universities" secondary onPress={()=>nav.navigate('Compare')}/>}
 <Button label={isEvent?(canRegister(item)?'Request event registration':'Registration unavailable'):'Book Free Counselling'} disabled={isEvent&&!canRegister(item)} onPress={()=>nav.navigate('Booking',{kind,referenceId:id,destination:group==='STUDY_DESTINATIONS'?text(item.name):text(item.country||'Undecided / Multiple')})}/>
 </Screen>;
}
export function SavedScreen(){const app=useApp(),nav=useNavigation<Nav>();const [group,setGroup]=useState('All');const entries=collections.flatMap(g=>app.data[g.key].filter(item=>app.saved.includes(recordKey(g.key,item))).map(item=>({group:g.key,item}))).filter(x=>group==='All'||x.group===group);
 return <Screen><Heading title="My Saved Collection" copy="Your shortlist is saved on this device."/><Chips items={['All',...collections.map(g=>g.title)]} selected={collections.find(g=>g.key===group)?.title||'All'} onSelect={v=>setGroup(collections.find(g=>g.title===v)?.key||'All')}/>{entries.length?entries.map(({group,item})=><ItemCard key={recordKey(group,item)} item={item} saved onSave={()=>app.toggleSave(recordKey(group,item))} onPress={()=>openItem(nav,group,item)}/>):<Empty message="Save destinations, universities, guides and services to see them here."/>}</Screen>;
}
export function SearchScreen(){
 const app=useApp(),nav=useNavigation<Nav>();const [query,setQuery]=useState(''),[filter,setFilter]=useState('All');
 const results=collections.filter(g=>filter==='All'||g.title===filter).flatMap(g=>filterRecords(app.data[g.key],query).map(item=>({group:g.key,item})));
 return <View style={s.screen}><View style={{padding:16,gap:12}}><Field label="Search everything" value={query} onChangeText={setQuery} autoFocus onSubmitEditing={()=>app.remember(query)}/><Chips items={['All',...collections.map(g=>g.title)]} selected={filter} onSelect={setFilter}/>{!query&&app.recent.length>0&&<><T style={s.label}>Recent searches</T><Chips items={app.recent} selected="" onSelect={setQuery}/><Button label="Clear recent searches" secondary onPress={app.clearRecent}/></>}</View><FlatList data={results} keyExtractor={x=>recordKey(x.group,x.item)} contentContainerStyle={{padding:16,gap:12}} keyboardShouldPersistTaps="handled" ListEmptyComponent={<Empty message="No matches found."/>} renderItem={({item:x})=><Card><T style={s.eyebrow}>{collections.find(g=>g.key===x.group)?.title}</T><Button label={title(x.item)} secondary onPress={()=>{app.remember(query);openItem(nav,x.group,x.item);}}/></Card>}/></View>;
}
export function CompareScreen(){const app=useApp();const [ids,setIds]=useState<string[]>(app.data.GLOBAL_UNIVERSITIES.slice(0,2).map(u=>String(u.id))),[query,setQuery]=useState(''),[slot,setSlot]=useState(0);const selected=ids.map(id=>app.data.GLOBAL_UNIVERSITIES.find(u=>String(u.id)===id));const rows=Object.keys(selected[0]||{}).filter(k=>!['id',...imageKeys].includes(k));
 return <Screen><Heading title="University Comparison" copy="Compare every published field side-by-side. Missing information remains Not provided."/><Chips items={['University 1','University 2']} selected={'University '+(slot+1)} onSelect={v=>setSlot(v==='University 1'?0:1)}/><Field label="Find a university" value={query} onChangeText={setQuery}/><ScrollView horizontal contentContainerStyle={{gap:8}}>{filterRecords(app.data.GLOBAL_UNIVERSITIES,query).map(u=><Button key={String(u.id)} label={title(u)} secondary disabled={ids[1-slot]===String(u.id)} onPress={()=>setIds(prev=>{const next=[...prev];next[slot]=String(u.id);return next;})}/>)}</ScrollView>{selected.some(u=>!u)?<Empty message="Two published universities are required to compare."/>:<Card>{rows.map(key=><View key={key} style={{gap:8,borderBottomWidth:1,borderBottomColor:colors.line,paddingBottom:12}}><T style={s.label}>{label(key)}</T><View style={{flexDirection:'row',gap:16}}>{selected.map((u,i)=><T key={i} style={{flex:1}}>{text(u?.[key])}</T>)}</View></View>)}</Card>}</Screen>;
}
export function VisaScreen({route}:{route:RouteProp<Routes,'Visa'>}){const app=useApp();const [country,setCountry]=useState(route.params?.country||Object.keys(app.data.VISA_ROADMAP_DATA)[0]);const roadmap=app.data.VISA_ROADMAP_DATA[country];const docs=(roadmap?.requiredDocumentsChecklist||[]) as RecordData[];
 return <Screen><Heading title="Interactive Visa Process Roadmap"/><Chips items={Object.keys(app.data.VISA_ROADMAP_DATA)} selected={country} onSelect={setCountry}/>{roadmap?<><Card><Fields value={roadmap} omit={['steps','requiredDocumentsChecklist']}/></Card><Heading title="Required Documents Checklist" copy="Track your preparation. Your selections stay on this device."/>{docs.map(doc=><Card key={String(doc.id)}><Check label={text(doc.name)} value={app.checks.includes(String(doc.id))} onPress={()=>app.toggleCheck(String(doc.id))}/><Fields value={doc} omit={['id','name']}/></Card>)}<Heading title="Consular milestones"/>{((roadmap.steps||[]) as RecordData[]).map((step,i)=><Card key={i}><Fields value={step}/></Card>)}</>:<Empty/>}</Screen>;
}
export function AboutScreen(){const app=useApp();return <Screen><Heading title="About Trans Globe"/><Card><Fields value={app.data.ABOUT_INFO}/></Card><Card><Fields value={app.data.GEIC_BRAND}/></Card></Screen>;}
export function ContactScreen(){const app=useApp(),nav=useNavigation<Nav>(),brand=app.data.GEIC_BRAND;return <Screen><Heading title="Contact Trans Globe Indore"/><Card><T style={s.title}>{text(brand.address)}</T><T>{text(brand.displayPhone)}</T><T>{text(brand.email)}</T><T>Office hours: {text(brand.officeHours)}</T><Button label="Call counsellor" onPress={()=>void openExternal('tel:'+text(brand.phone))}/><Button label="Email counsellor" secondary onPress={()=>void openExternal('mailto:'+text(brand.email))}/><Button label="WhatsApp" secondary onPress={()=>void openExternal('whatsapp://send?phone='+text(brand.phone).replace(/\D/g,''))}/><Button label="Open map" secondary onPress={()=>void openExternal((Platform.OS==='ios'?'maps:?q=':'geo:0,0?q=')+encodeURIComponent(text(brand.address)))}/></Card><Button label="Send an enquiry" onPress={()=>nav.navigate('Booking')}/></Screen>;}
export function MenuScreen(){const nav=useNavigation<Nav>();return <Screen><Heading title="Tranglobe-GEIC App"/>{collections.map(g=><Button key={g.key} label={g.title} secondary icon={g.icon} onPress={()=>nav.navigate('Directory',{collection:g.key})}/>)}<Button label="My Saved Collection" secondary onPress={()=>nav.navigate('Saved')}/><Button label="Compare Universities" secondary onPress={()=>nav.navigate('Compare')}/><Button label="Visa Roadmap" secondary onPress={()=>nav.navigate('Visa')}/><Button label="About" secondary onPress={()=>nav.navigate('About')}/><Button label="Contact Us" secondary onPress={()=>nav.navigate('Contact')}/><Button label="Book Free Counselling" onPress={()=>nav.navigate('Booking')}/></Screen>;}
